global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Linq;
global using System.Linq.Providers;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.SourceGeneration;
global using System.Text;
global using Sudoku.Concepts;
global using Sudoku.Concepts.Coordinates;
global using Sudoku.Linq;
global using static System.Numerics.BitOperations;
global using static Sudoku.Concepts.ConclusionType;
global using static Sudoku.SolutionFields;
