[assembly: InternalsVisibleTo("Sudoku.Core")]
[assembly: InternalsVisibleTo("Sudoku.CommandLine")]
[assembly: InternalsVisibleTo("Sudoku.Solving.Logical")]
[assembly: InternalsVisibleTo("Sudoku.Platforms.QQ")]
[assembly: InternalsVisibleTo("SudokuStudio")]
