global using System.Buffers;
global using System.ComponentModel;
global using System.Runtime.Intrinsics;
global using System.Runtime.Messages;
global using System.SourceGeneration;
global using System.Text.Encodings.Web;
global using static System.Math;
global using static System.MathF;
global using Bits = System.ReadOnlySpan<int>;
global using BitEnumerator = System.ReadOnlySpan<int>.Enumerator;
