global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.CodeGen;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Shapes;
global using Sudoku.Concepts;
global using Sudoku.Presentation;
global using Sudoku.Presentation.Nodes;
global using Windows.Foundation;
global using Windows.UI;
global using static System.Numerics.BitOperations;
global using static Sudoku.Runtime.AnalysisServices.CommonReadOnlies;
global using GridLayout = Microsoft.UI.Xaml.Controls.Grid;
global using Grid = Sudoku.Concepts.Collections.Grid;
