//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudokuStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudokuStudio.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string _DifficultyLevel_Easy {
            get {
                return ResourceManager.GetString("_DifficultyLevel_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiendish.
        /// </summary>
        internal static string _DifficultyLevel_Fiendish {
            get {
                return ResourceManager.GetString("_DifficultyLevel_Fiendish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string _DifficultyLevel_Hard {
            get {
                return ResourceManager.GetString("_DifficultyLevel_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        internal static string _DifficultyLevel_Moderate {
            get {
                return ResourceManager.GetString("_DifficultyLevel_Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightmare.
        /// </summary>
        internal static string _DifficultyLevel_Nightmare {
            get {
                return ResourceManager.GetString("_DifficultyLevel_Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string _DifficultyLevel_Unknown {
            get {
                return ResourceManager.GetString("_DifficultyLevel_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Studio.
        /// </summary>
        internal static string _ProgramName {
            get {
                return ResourceManager.GetString("_ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Available Steps.
        /// </summary>
        internal static string AnalyzePage_AllStepsInCurrentGrid {
            get {
                return ResourceManager.GetString("AnalyzePage_AllStepsInCurrentGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        internal static string AnalyzePage_AnalyzeButton {
            get {
                return ResourceManager.GetString("AnalyzePage_AnalyzeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0:P}.
        /// </summary>
        internal static string AnalyzePage_AnalyzerProgress {
            get {
                return ResourceManager.GetString("AnalyzePage_AnalyzerProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will clear the puzzle, returning the puzzle to empty status. Are you sure?.
        /// </summary>
        internal static string AnalyzePage_AreYouSureToReturnToEmpty {
            get {
                return ResourceManager.GetString("AnalyzePage_AreYouSureToReturnToEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AnalyzePage_Cancel {
            get {
                return ResourceManager.GetString("AnalyzePage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently chosen file is empty..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_FileIsEmpty {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently chosen file is too large - it is oversized..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_FileIsTooLarge {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_FileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The puzzle in the file is invalid to be parsed..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_GridIsInvalidToParse {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_GridIsInvalidToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The puzzle in the file does not contain a unique solution - it contains multiple solutions, or the puzzle is invalid..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_GridIsNotUnique {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_GridIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the file picker because the current program is snapped, which is disallowed..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_ProgramIsSnapped {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_ProgramIsSnapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the format that you want to save:.
        /// </summary>
        internal static string AnalyzePage_ChooseFormats {
            get {
                return ResourceManager.GetString("AnalyzePage_ChooseFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string AnalyzePage_Clear {
            get {
                return ResourceManager.GetString("AnalyzePage_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Commands.
        /// </summary>
        internal static string AnalyzePage_CommonCommands {
            get {
                return ResourceManager.GetString("AnalyzePage_CommonCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string AnalyzePage_CopyCommandName {
            get {
                return ResourceManager.GetString("AnalyzePage_CopyCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy image.
        /// </summary>
        internal static string AnalyzePage_CopyPictureCommandName {
            get {
                return ResourceManager.GetString("AnalyzePage_CopyPictureCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current grid format.
        /// </summary>
        internal static string AnalyzePage_CurrentGridFormat {
            get {
                return ResourceManager.GetString("AnalyzePage_CurrentGridFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current grid format, but all values will be treated as givens.
        /// </summary>
        internal static string AnalyzePage_CurrentGridFormatTreatingModifiableAsGiven {
            get {
                return ResourceManager.GetString("AnalyzePage_CurrentGridFormatTreatingModifiableAsGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty distribution.
        /// </summary>
        internal static string AnalyzePage_DifficultyChartTitle {
            get {
                return ResourceManager.GetString("AnalyzePage_DifficultyChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string AnalyzePage_DifficultyLevel {
            get {
                return ResourceManager.GetString("AnalyzePage_DifficultyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string AnalyzePage_DifficultyMax {
            get {
                return ResourceManager.GetString("AnalyzePage_DifficultyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string AnalyzePage_DifficultyTotal {
            get {
                return ResourceManager.GetString("AnalyzePage_DifficultyTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Empty&gt;.
        /// </summary>
        internal static string AnalyzePage_EmptyGrid {
            get {
                return ResourceManager.GetString("AnalyzePage_EmptyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure....
        /// </summary>
        internal static string AnalyzePage_Ensure {
            get {
                return ResourceManager.GetString("AnalyzePage_Ensure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel compatible format.
        /// </summary>
        internal static string AnalyzePage_ExcelFormat {
            get {
                return ResourceManager.GetString("AnalyzePage_ExcelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string AnalyzePage_FailedToOpenFilePicker {
            get {
                return ResourceManager.GetString("AnalyzePage_FailedToOpenFilePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter gathered steps.
        /// </summary>
        internal static string AnalyzePage_FilterGatheredSteps {
            get {
                return ResourceManager.GetString("AnalyzePage_FilterGatheredSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering expression is invalid. Please check..
        /// </summary>
        internal static string AnalyzePage_FilteringFailedDueToInvalidExpression {
            get {
                return ResourceManager.GetString("AnalyzePage_FilteringFailedDueToInvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix grid.
        /// </summary>
        internal static string AnalyzePage_FixGrid {
            get {
                return ResourceManager.GetString("AnalyzePage_FixGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather steps.
        /// </summary>
        internal static string AnalyzePage_GatherStepsInCurrentGrid {
            get {
                return ResourceManager.GetString("AnalyzePage_GatherStepsInCurrentGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Givens count: .
        /// </summary>
        internal static string AnalyzePage_GivensCount {
            get {
                return ResourceManager.GetString("AnalyzePage_GivensCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodoku library compatible format.
        /// </summary>
        internal static string AnalyzePage_HodokuFormat {
            get {
                return ResourceManager.GetString("AnalyzePage_HodokuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial grid format.
        /// </summary>
        internal static string AnalyzePage_InitialGridFormat {
            get {
                return ResourceManager.GetString("AnalyzePage_InitialGridFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Minimal puzzle: .
        /// </summary>
        internal static string AnalyzePage_IsMinimal {
            get {
                return ResourceManager.GetString("AnalyzePage_IsMinimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Charts.
        /// </summary>
        internal static string AnalyzePage_LiveCharts {
            get {
                return ResourceManager.GetString("AnalyzePage_LiveCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (at least one hint can be removed, e.g. {0}).
        /// </summary>
        internal static string AnalyzePage_MinimalResult_AtLeastOneHintCanBeRemoved {
            get {
                return ResourceManager.GetString("AnalyzePage_MinimalResult_AtLeastOneHintCanBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (puzzle is not unique, or unfixed).
        /// </summary>
        internal static string AnalyzePage_MinimalResult_NotUniquePuzzle {
            get {
                return ResourceManager.GetString("AnalyzePage_MinimalResult_NotUniquePuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AnalyzePage_MinimalResult_Yes {
            get {
                return ResourceManager.GetString("AnalyzePage_MinimalResult_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple-line simple grid format.
        /// </summary>
        internal static string AnalyzePage_MultipleLineGridFormat {
            get {
                return ResourceManager.GetString("AnalyzePage_MultipleLineGridFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New puzzle.
        /// </summary>
        internal static string AnalyzePage_NewPuzzle {
            get {
                return ResourceManager.GetString("AnalyzePage_NewPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AnalyzePage_Okay {
            get {
                return ResourceManager.GetString("AnalyzePage_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string AnalyzePage_OpenFile {
            get {
                return ResourceManager.GetString("AnalyzePage_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSudoku compatible format.
        /// </summary>
        internal static string AnalyzePage_OpenSudokuFormat {
            get {
                return ResourceManager.GetString("AnalyzePage_OpenSudokuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string AnalyzePage_PasteCommandName {
            get {
                return ResourceManager.GetString("AnalyzePage_PasteCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pencilmarked format.
        /// </summary>
        internal static string AnalyzePage_PencilmarkFormat {
            get {
                return ResourceManager.GetString("AnalyzePage_PencilmarkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        internal static string AnalyzePage_PivotItem_BasicOperations {
            get {
                return ResourceManager.GetString("AnalyzePage_PivotItem_BasicOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text code: .
        /// </summary>
        internal static string AnalyzePage_PuzzleCode {
            get {
                return ResourceManager.GetString("AnalyzePage_PuzzleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle Data.
        /// </summary>
        internal static string AnalyzePage_PuzzleData {
            get {
                return ResourceManager.GetString("AnalyzePage_PuzzleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple solutions.
        /// </summary>
        internal static string AnalyzePage_PuzzleHasMultipleSolutions {
            get {
                return ResourceManager.GetString("AnalyzePage_PuzzleHasMultipleSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No solution.
        /// </summary>
        internal static string AnalyzePage_PuzzleHasNoSolution {
            get {
                return ResourceManager.GetString("AnalyzePage_PuzzleHasNoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique solution.
        /// </summary>
        internal static string AnalyzePage_PuzzleHasUniqueSolution {
            get {
                return ResourceManager.GetString("AnalyzePage_PuzzleHasUniqueSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique solution, but with grid being unfixed.
        /// </summary>
        internal static string AnalyzePage_PuzzleHasUniqueSolutionButUnfixed {
            get {
                return ResourceManager.GetString("AnalyzePage_PuzzleHasUniqueSolutionButUnfixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string AnalyzePage_Redo {
            get {
                return ResourceManager.GetString("AnalyzePage_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string AnalyzePage_ResetCommandName {
            get {
                return ResourceManager.GetString("AnalyzePage_ResetCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save!.
        /// </summary>
        internal static string AnalyzePage_SaveAsButtonContent {
            get {
                return ResourceManager.GetString("AnalyzePage_SaveAsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AnalyzePage_SaveFile {
            get {
                return ResourceManager.GetString("AnalyzePage_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string AnalyzePage_SaveFileAnother {
            get {
                return ResourceManager.GetString("AnalyzePage_SaveFileAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input search expression, e.g. name like &quot;[Uu]nique\sRectangle.*&quot;.
        /// </summary>
        internal static string AnalyzePage_SearchAllSteps {
            get {
                return ResourceManager.GetString("AnalyzePage_SearchAllSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string AnalyzePage_SelectAll {
            get {
                return ResourceManager.GetString("AnalyzePage_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Description:.
        /// </summary>
        internal static string AnalyzePage_SimpleDescription {
            get {
                return ResourceManager.GetString("AnalyzePage_SimpleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solving Path.
        /// </summary>
        internal static string AnalyzePage_StepDetail {
            get {
                return ResourceManager.GetString("AnalyzePage_StepDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        internal static string AnalyzePage_SucceedToSaveFile {
            get {
                return ResourceManager.GetString("AnalyzePage_SucceedToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukaku format.
        /// </summary>
        internal static string AnalyzePage_SukakuFormat {
            get {
                return ResourceManager.GetString("AnalyzePage_SukakuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure!.
        /// </summary>
        internal static string AnalyzePage_Sure {
            get {
                return ResourceManager.GetString("AnalyzePage_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string AnalyzePage_TechniqueCount {
            get {
                return ResourceManager.GetString("AnalyzePage_TechniqueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty Rating (≥ 1.0 and ≤ 12.0):.
        /// </summary>
        internal static string AnalyzePage_TechniqueDifficultyRating {
            get {
                return ResourceManager.GetString("AnalyzePage_TechniqueDifficultyRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of Path:.
        /// </summary>
        internal static string AnalyzePage_TechniqueIndex {
            get {
                return ResourceManager.GetString("AnalyzePage_TechniqueIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique Name:.
        /// </summary>
        internal static string AnalyzePage_TechniqueName {
            get {
                return ResourceManager.GetString("AnalyzePage_TechniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique.
        /// </summary>
        internal static string AnalyzePage_TechniqueOrTechniqueGroupName {
            get {
                return ResourceManager.GetString("AnalyzePage_TechniqueOrTechniqueGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string AnalyzePage_TechniquesTable {
            get {
                return ResourceManager.GetString("AnalyzePage_TechniquesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide candidates.
        /// </summary>
        internal static string AnalyzePage_ToggleDisplayingCandidates {
            get {
                return ResourceManager.GetString("AnalyzePage_ToggleDisplayingCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Undefined&gt;.
        /// </summary>
        internal static string AnalyzePage_UndefinedGrid {
            get {
                return ResourceManager.GetString("AnalyzePage_UndefinedGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string AnalyzePage_Undo {
            get {
                return ResourceManager.GetString("AnalyzePage_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfix grid.
        /// </summary>
        internal static string AnalyzePage_UnfixGrid {
            get {
                return ResourceManager.GetString("AnalyzePage_UnfixGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Uniqueness: .
        /// </summary>
        internal static string AnalyzePage_Uniqueness {
            get {
                return ResourceManager.GetString("AnalyzePage_Uniqueness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable picture format.
        /// </summary>
        internal static string FileExtension_Picture {
            get {
                return ResourceManager.GetString("FileExtension_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain text format.
        /// </summary>
        internal static string FileExtension_PlainTextDescription {
            get {
                return ResourceManager.GetString("FileExtension_PlainTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku puzzle format.
        /// </summary>
        internal static string FileExtension_TextDescription {
            get {
                return ResourceManager.GetString("FileExtension_TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        internal static string MainWindow_Analyze {
            get {
                return ResourceManager.GetString("MainWindow_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solving &amp; Analysis.
        /// </summary>
        internal static string MainWindow_AnalyzePageTitle {
            get {
                return ResourceManager.GetString("MainWindow_AnalyzePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MainWindow_Menu {
            get {
                return ResourceManager.GetString("MainWindow_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string MainWindow_Search {
            get {
                return ResourceManager.GetString("MainWindow_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings &amp; Preferences.
        /// </summary>
        internal static string MainWindow_SettingsPageTitle {
            get {
                return ResourceManager.GetString("MainWindow_SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku.
        /// </summary>
        internal static string Sudoku {
            get {
                return ResourceManager.GetString("Sudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please drop the file here.
        /// </summary>
        internal static string SudokuPane_DropSudokuFileHere {
            get {
                return ResourceManager.GetString("SudokuPane_DropSudokuFileHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sets or eliminations: .
        /// </summary>
        internal static string SudokuPane_RightClickMenu_InputSetter {
            get {
                return ResourceManager.GetString("SudokuPane_RightClickMenu_InputSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: !1-4、!567、!8、9.
        /// </summary>
        internal static string SudokuPane_RightClickMenu_InputSetterPlaceholder {
            get {
                return ResourceManager.GetString("SudokuPane_RightClickMenu_InputSetterPlaceholder", resourceCulture);
            }
        }
    }
}
