//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudokuStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudokuStudio.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Studio.
        /// </summary>
        internal static string _ProgramName {
            get {
                return ResourceManager.GetString("_ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently chosen file is empty..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_FileIsEmpty {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently chosen file is too large - it is oversized..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_FileIsTooLarge {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_FileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The puzzle in the file is invalid to be parsed..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_GridIsInvalidToParse {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_GridIsInvalidToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The puzzle in the file does not contain a unique solution - it contains multiple solutions, or the puzzle is invalid..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_GridIsNotUnique {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_GridIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the file picker because the current program is snapped, which is disallowed..
        /// </summary>
        internal static string AnalyzePage_CannotOpenFile_ProgramIsSnapped {
            get {
                return ResourceManager.GetString("AnalyzePage_CannotOpenFile_ProgramIsSnapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string AnalyzePage_FailedToOpenFilePicker {
            get {
                return ResourceManager.GetString("AnalyzePage_FailedToOpenFilePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New puzzle.
        /// </summary>
        internal static string AnalyzePage_NewPuzzle {
            get {
                return ResourceManager.GetString("AnalyzePage_NewPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AnalyzePage_Okay {
            get {
                return ResourceManager.GetString("AnalyzePage_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        internal static string AnalyzePage_OpenFile {
            get {
                return ResourceManager.GetString("AnalyzePage_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        internal static string AnalyzePage_PivotItem_BasicOperations {
            get {
                return ResourceManager.GetString("AnalyzePage_PivotItem_BasicOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        internal static string MainWindow_Analyze {
            get {
                return ResourceManager.GetString("MainWindow_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solving &amp; Analysis.
        /// </summary>
        internal static string MainWindow_AnalyzePageTitle {
            get {
                return ResourceManager.GetString("MainWindow_AnalyzePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MainWindow_Menu {
            get {
                return ResourceManager.GetString("MainWindow_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string MainWindow_Search {
            get {
                return ResourceManager.GetString("MainWindow_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings &amp; Preferences.
        /// </summary>
        internal static string MainWindow_SettingsPageTitle {
            get {
                return ResourceManager.GetString("MainWindow_SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please drop the file here.
        /// </summary>
        internal static string SudokuPane_DropSudokuFileHere {
            get {
                return ResourceManager.GetString("SudokuPane_DropSudokuFileHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sets or eliminations:.
        /// </summary>
        internal static string SudokuPane_RightClickMenu_InputSetter {
            get {
                return ResourceManager.GetString("SudokuPane_RightClickMenu_InputSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: !1-4、!567、!8、9.
        /// </summary>
        internal static string SudokuPane_RightClickMenu_InputSetterPlaceholder {
            get {
                return ResourceManager.GetString("SudokuPane_RightClickMenu_InputSetterPlaceholder", resourceCulture);
            }
        }
    }
}
