global using System;
global using System.Diagnostics.CodeAnalysis;
global using System.Dynamic;
global using System.IO;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.Versioning;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Navigation;
global using Microsoft.UI.Xaml.Shapes;
global using Sudoku.Data;
global using Sudoku.Solving.BruteForces;
global using Sudoku.UI.CustomControls;
global using Sudoku.UI.Data;
global using Sudoku.UI.Pages.MainWindow;
global using Sudoku.UI.Resources;
global using Windows.ApplicationModel.DataTransfer;
global using Windows.Storage;
global using Windows.UI;
global using Grid = Microsoft.UI.Xaml.Controls.Grid;
global using SudokuGrid = Sudoku.Data.Grid;
