global using System;
global using System.Diagnostics.CodeAnalysis;
global using System.Dynamic;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Runtime.Versioning;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using Sudoku.Drawing;
global using Sudoku.UI.CustomControls;
global using Sudoku.UI.Interactions;
global using Sudoku.UI.Pages.MainWindow;
global using Sudoku.UI.Resources;
global using gdip = System.Drawing;
