[assembly: InternalsVisibleTo("Sudoku.SourceGeneration")]
[assembly: InternalsVisibleTo("Sudoku.Analytics.StepSearchers.SourceGeneration")]
[assembly: InternalsVisibleTo("SystemExtensions.SourceGeneration")]
[assembly: InternalsVisibleTo("SudokuStudio.SourceGeneration")]
[assembly: SuppressMessage("Design", "CA1050:Declare types in namespaces", Justification = "<Pending>")]
