global using System;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using Microsoft.UI.Composition;
global using Microsoft.UI.Composition.SystemBackdrops;
global using Microsoft.UI.Xaml;
global using SudokuStudio.AppLifecycle;
global using SudokuStudio.Interop;
global using SudokuStudio.Views.Windows;
global using WinRT;
global using static Sudoku.Resources.MergedResources;
global using winsys = Windows.System;
