#pragma warning disable CS8981

global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.CodeGen;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using Microsoft.UI;
global using Microsoft.UI.Composition;
global using Microsoft.UI.Composition.SystemBackdrops;
global using Microsoft.UI.Windowing;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Input;
global using Microsoft.UI.Xaml.Markup;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Media.Animation;
global using Sudoku.Concepts;
global using Sudoku.Text.Notations;
global using SudokuStudio.AppLifecycle;
global using SudokuStudio.Interop;
global using SudokuStudio.Views.Controls;
global using SudokuStudio.Views.Pages;
global using SudokuStudio.Views.Windows;
global using Windows.Graphics;
global using Windows.UI;
global using WinRT;
global using WinRT.Interop;
global using static System.Math;
global using static Sudoku.Resources.MergedResources;
global using static SudokuStudio.Resources.ResourceDictionary;
global using GridLayout = Microsoft.UI.Xaml.Controls.Grid;
global using Grid = Sudoku.Concepts.Grid;
global using winsys = Windows.System;
