global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.Drawing.Imaging;
global using System.Drawing.Text;
global using System.Runtime.Versioning;
global using System.SourceGeneration;
global using Sudoku.Analytics;
global using Sudoku.Drawing.TextRendering;
global using Sudoku.Gdip;
global using Sudoku.Operations;
global using Sudoku.Rendering;
global using Sudoku.Rendering.Nodes;
global using Sudoku.Rendering.Nodes.Grouped;
global using Sudoku.Rendering.Nodes.Shapes;
global using static System.MathF;
global using static Sudoku.Drawing.ProjectWideConstants;
