global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeGen;
global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.Drawing.Imaging;
global using System.Drawing.Text;
global using System.IO;
global using System.Linq;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.Versioning;
global using Sudoku.Concepts;
global using Sudoku.Drawing.TextRendering;
global using Sudoku.Gdip;
global using Sudoku.Presentation;
global using Sudoku.Presentation.Nodes;
global using Sudoku.Solving;
global using static System.MathF;
global using static Sudoku.Drawing.ProjectWideConstants;
global using static Sudoku.Runtime.MaskServices.MaskOperations;
