global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Numerics;
global using System.Resources;
global using System.Runtime.CompilerServices;
global using System.SourceGeneration;
global using Sudoku.Concepts.Coordinates;
global using static System.Numerics.BitOperations;
global using static Sudoku.SolutionFields;
