global using System;
global using System.Collections.Specialized;
global using System.ComponentModel;
global using System.Runtime.CompilerServices;
global using System.Windows.Input;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Sudoku.UI.Windows.Controls;
global using Sudoku.UI.Windows.Pages;
global using SudokuGrid = Sudoku.Data.Grid;
