global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Threading;
global using System.Threading.Tasks;
global using Sudoku.Algorithms.Collections;
global using Sudoku.Algorithms.Solving;
global using Sudoku.Analytics;
global using Sudoku.Concepts;
global using static System.Math;
global using static System.Runtime.CompilerServices.Unsafe;
global using static Sudoku.SolutionWideReadOnlyFields;
