global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.CodeGen;
global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.Drawing.Text;
global using System.Linq;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.Versioning;
global using Sudoku.Concepts;
global using Sudoku.Concepts.Collections;
global using Sudoku.Concepts.Solving;
global using Sudoku.Presentation;
global using Sudoku.Presentation.Nodes;
global using static System.Math;
