global using System;
global using System.Collections.Generic;
global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.Drawing.Imaging;
global using System.Drawing.Text;
global using System.IO;
global using System.Linq;
global using System.Linq.Providers;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.Versioning;
global using Sudoku.Concepts;
global using Sudoku.Drawing.Nodes;
global using Sudoku.Runtime.MaskServices;
global using static System.MathF;
global using static Sudoku.Concepts.ConclusionType;
