[assembly: InternalsVisibleTo("Sudoku.Analytics.CodeGen")]
[assembly: InternalsVisibleTo("Sudoku.Diagnostics.CodeGen")]
[assembly: InternalsVisibleTo("Sudoku.Solving.Logical.CodeGen")]
[assembly: InternalsVisibleTo("SystemExtensions.CodeGen")]
[assembly: InternalsVisibleTo("SudokuStudio.CodeGen")]
