global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Xml;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.Text;
global using Kind = Microsoft.CodeAnalysis.TypeKind;
