global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Encodings.Web;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using HuajiTech.UnmanagedExports;
global using Sudoku.Bot.Oicq.Concepts;
global using Sudoku.Bot.Oicq.Concepts.CodeProviders;
global using Sudoku.Bot.Oicq.Eventing;
global using Sudoku.Bot.Oicq.Extensibility;
global using Sudoku.Bot.Oicq.Extensibility.Handlers;
global using static Sudoku.Bot.Oicq.Resources.ResourcesRouter;
