/// This file stores built-in <see cref="Sudoku.Analytics.StepSearcher"/> instances,
/// in order to create default collection for type <see cref="Sudoku.Analytics.StepSearcherPool.BuiltIn"/>.

#pragma warning disable format
using static Sudoku.Analytics.Metadata.StepSearcherLevel;
using static Sudoku.Analytics.Metadata.StepSearcherRunningArea;

[assembly: StepSearcherImport<                        SingleStepSearcher>(Elementary)]
[assembly: StepSearcherImport<              LockedCandidatesStepSearcher>(Elementary)]
[assembly: StepSearcherImport<                        SubsetStepSearcher>(  Moderate)]
[assembly: StepSearcherImport<                    NormalFishStepSearcher>(  Moderate)]
[assembly: StepSearcherImport<                TwoStrongLinksStepSearcher>(  Moderate)]
[assembly: StepSearcherImport<                   RegularWingStepSearcher>(  Moderate)]
[assembly: StepSearcherImport<                         WWingStepSearcher>(  Moderate)]
[assembly: StepSearcherImport<              MultiBranchWWingStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<               UniqueRectangleStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<        AlmostLockedCandidatesStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<                      SueDeCoqStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<            SueDeCoq3DimensionStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<                    UniqueLoopStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<             ExtendedRectangleStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<                EmptyRectangleStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<                  UniqueMatrixStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<                 UniquePolygonStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<              QiuDeadlyPatternStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<         BivalueUniversalGraveStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<  ReverseBivalueUniversalGraveStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<           UniquenessClueCoverStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<               RwDeadlyPatternStepSearcher>(  Moderate, Areas =      None)]
//[assembly: StepSearcherImport<EmptyRectangleIntersectionPairStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<                      FireworkStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<     GurthSymmetricalPlacementStepSearcher>(Elementary)]
//[assembly: StepSearcherImport<           NonMultipleChainingStepSearcher>(      Hard)]
//[assembly: StepSearcherImport<            AlmostLockedSetsXzStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<        AlmostLockedSetsXyWingStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<         AlmostLockedSetsWWingStepSearcher>(  Moderate)]
//[assembly: StepSearcherImport<                      GuardianStepSearcher>(      Hard)]
//[assembly: StepSearcherImport<                   ComplexFishStepSearcher>(      Hard)]
//[assembly: StepSearcherImport<                BivalueOddagonStepSearcher>(      Hard)]
//[assembly: StepSearcherImport<              ChromaticPatternStepSearcher>(      Hard)]
//[assembly: StepSearcherImport<                  DeathBlossomStepSearcher>(      Hard, Areas =      None)]
//[assembly: StepSearcherImport<              MultipleChainingStepSearcher>(      Hard)]
//[assembly: StepSearcherImport<                   BowmanBingoStepSearcher>(      Hard, Areas =      None)]
//[assembly: StepSearcherImport<                      TemplateStepSearcher>(      Hard, Areas =      None)]
//[assembly: StepSearcherImport<                PatternOverlayStepSearcher>(      Hard, Areas = Gathering)]
//[assembly: StepSearcherImport<                  JuniorExocetStepSearcher>(  Fiendish)]
//[assembly: StepSearcherImport<                  SeniorExocetStepSearcher>(  Fiendish, Areas =      None)]
//[assembly: StepSearcherImport<                    DominoLoopStepSearcher>(  Fiendish)]
//[assembly: StepSearcherImport<         MultisectorLockedSetsStepSearcher>(  Fiendish)]
//[assembly: StepSearcherImport<      AdvancedMultipleChainingStepSearcher>(  Fiendish, Areas =      None)]
[assembly: StepSearcherImport<                    BruteForceStepSearcher>(    Hidden, Areas = Searching)]
