global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using Sudoku.Workflow.Bot.Oicq.Annotations;
global using Sudoku.Workflow.Bot.Oicq.ComponentModel;
