global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.CommandLine;
global using System.Diagnostics.CodeAnalysis;
global using System.Drawing;
global using System.IO;
global using System.Linq;
global using System.Net.NetworkInformation;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.Versioning;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using Mirai.Net.Data.Messages;
global using Mirai.Net.Data.Messages.Concretes;
global using Mirai.Net.Data.Messages.Receivers;
global using Mirai.Net.Data.Shared;
global using Mirai.Net.Modules;
global using Mirai.Net.Sessions;
global using Mirai.Net.Sessions.Http.Managers;
global using Mirai.Net.Utils.Scaffolds;
global using Sudoku.Algorithms.Generating;
global using Sudoku.Analytics;
global using Sudoku.Analytics.Categorization;
global using Sudoku.Analytics.Formatting;
global using Sudoku.Analytics.Metadata;
global using Sudoku.Analytics.Steps;
global using Sudoku.Concepts;
global using Sudoku.Drawing;
global using Sudoku.Rendering;
global using Sudoku.Rendering.Nodes;
global using Sudoku.Rendering.Nodes.Shapes;
global using Sudoku.Runtime.MaskServices;
global using Sudoku.Workflow.Bot.Oicq.Annotations;
global using Sudoku.Workflow.Bot.Oicq.ComponentModel;
global using Sudoku.Workflow.Bot.Oicq.Lifecycle;
global using Sudoku.Workflow.Bot.Oicq.Operation;
global using Sudoku.Workflow.Bot.Oicq.Parsing;
global using Sudoku.Workflow.Bot.Oicq.RootCommands;
global using Sudoku.Workflow.Bot.Oicq.RootCommands.Periodic;
global using Sudoku.Workflow.Bot.Oicq.ValueConverters;
global using static System.Algorithm.Sequences;
global using static System.Math;
global using static System.Text.Json.JsonSerializer;
global using static Sudoku.SolutionWideReadOnlyFields;
global using static Sudoku.Workflow.Bot.Oicq.Constants;
global using static Sudoku.Workflow.Bot.Oicq.Lifecycle.EnvironmentVariables;
global using Group = Mirai.Net.Data.Shared.Group;
global using SpecialFolder = System.Environment.SpecialFolder;
global using File = System.IO.File;
