global using System;
global using System.Collections.Immutable;
global using System.Diagnostics.CodeAnalysis;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CodeFixes;
global using Microsoft.CodeAnalysis.CodeRefactorings;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Testing;
global using Microsoft.CodeAnalysis.Diagnostics;
global using Microsoft.CodeAnalysis.Testing;
global using Microsoft.CodeAnalysis.Testing.Verifiers;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using static Sudoku.Diagnostics.CodeAnalysis.WellKnownDiagnosticDescriptors;
