global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Text.RegularExpressions;
global using System.Threading;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Diagnostics;
global using Microsoft.CodeAnalysis.Operations;
global using Sudoku.Diagnostics.CodeGen.Annotations;
global using static Microsoft.CodeAnalysis.CSharpAccessibility;
global using static Sudoku.Diagnostics.CodeAnalysis.WellKnownDiagnosticDescriptors;
global using NamedArguments = System.Collections.Immutable.ImmutableArray<System.Collections.Generic.KeyValuePair<string, Microsoft.CodeAnalysis.TypedConstant>>;
