global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Linq;
global using System.Reflection;
global using System.Threading;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using RootLevelSourceGeneration;
global using Sudoku.SourceGeneration.Handlers;
global using static RootLevelSourceGeneration.SolutionVersion;
