global using static System.Math;
global using static SudokuStudio.ProjectWideConstants;
global using static SudokuStudio.Strings.StringsAccessor;
global using Colors = Microsoft.UI.Colors;
global using DispatcherQueue = Microsoft.UI.Dispatching.DispatcherQueue;
global using GridLayout = Microsoft.UI.Xaml.Controls.Grid;
global using HorizontalAlignment = Microsoft.UI.Xaml.HorizontalAlignment;
global using LaunchActivatedEventArgs = Microsoft.UI.Xaml.LaunchActivatedEventArgs;
global using Geometry = Microsoft.UI.Xaml.Media.Geometry;
global using LineGeometry = Microsoft.UI.Xaml.Media.LineGeometry;
global using PathGeometry = Microsoft.UI.Xaml.Media.PathGeometry;
global using Path = Microsoft.UI.Xaml.Shapes.Path;
global using VerticalAlignment = Microsoft.UI.Xaml.VerticalAlignment;
global using PdfColors = QuestPDF.Helpers.Colors;
global using PdfContainer = QuestPDF.Infrastructure.IContainer;
global using Grid = Sudoku.Concepts.Grid;
global using SpecialFolder = System.Environment.SpecialFolder;
global using SystemPath = System.IO.Path;
global using Size = Windows.Foundation.Size;
