global using System;
global using System.Collections.Generic;
global using System.Resources;
global using System.Runtime.CompilerServices;
global using System.SourceGeneration;
global using System.Text;
global using Sudoku.Concepts;
global using Sudoku.Concepts.Primitive;
global using Sudoku.MinLex;
