namespace Sudoku.SourceGeneration;

/// <summary>
/// Represents a source generator that copies the whole method, and replaces some variables with cached fields.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed partial class CachedMethodGenerator : IIncrementalGenerator
{
	private const string InterceptorMethodCallerAttributeTypeFullName = "Sudoku.Runtime.InterceptorServices.InterceptorMethodCallerAttribute";

	private const string InterceptorInstanceTypesAttributeTypeFullName = "Sudoku.Runtime.InterceptorServices.InterceptorInstanceTypesAttribute";

	private const string CachedAttributeTypeFullName = "Sudoku.Runtime.InterceptorServices.CachedAttribute";

	private const string GeneratedNamespace = "Sudoku.Runtime.InterceptorServices.Generated";

	private const string InterceptsLocationAttributeFullName = "System.Runtime.CompilerServices.InterceptsLocationAttribute";

	private const string CommentLineBegin = "VARIABLE_DECLARATION_BEGIN";

	private const string CommentLineEnd = "VARIABLE_DECLARATION_END";

	private const string AttributeInsertionMatchString = "<<insert-here>>";


	/// <summary>
	/// Indicates the raw source code for intercepts location attribute.
	/// </summary>
	private static readonly string InterceptsLocationAttributeSourceCode =
		$$"""
		{{Banner.AutoGenerated}}

		#nullable enable

		namespace System.Runtime.CompilerServices;

		/// <summary>
		/// <para>
		/// Interceptors are an experimental compiler feature planned to ship in .NET 8 (with support for C# only).
		/// The feature may be subject to breaking changes or removal in a future release.
		/// </para>
		/// <para>
		/// An interceptor is a method which can declaratively substitute a call to an interceptable method with a call
		/// to itself at compile time.
		/// This substitution occurs by having the interceptor declare the source locations of the calls that it intercepts.
		/// This provides a limited facility to change the semantics of existing code
		/// by adding new code to a compilation (e.g. in a source generator).
		/// </para>
		/// </summary>
		/// <param name="filePath">The required file path.</param>
		/// <param name="line">The line.</param>
		/// <param name="character">The character position.</param>
		[global::System.AttributeUsageAttribute(global::System.AttributeTargets.Method, AllowMultiple = true)]
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{typeof(CachedMethodGenerator).FullName}}", "{{Value}}")]
		[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
		internal sealed partial class InterceptsLocationAttribute(string filePath, int line, int character) : global::System.Attribute
		{
			/// <summary>
			/// Indicates the target file path.
			/// </summary>
			public string FilePath { get; } = filePath;

			/// <summary>
			/// Indicates the line number.
			/// </summary>
			public int Line { get; } = line;

			/// <summary>
			/// Indicates the character number.
			/// </summary>
			public int Character { get; } = character;
		}
		""";

	private static readonly string[] ValidVariableNames = [
		"__EmptyCells",
		"__BivalueCells",
		"__CandidatesMap",
		"__DigitsMap",
		"__ValuesMap"
	];


	/// <inheritdoc/>
	/// <remarks>
	/// This generator will aim to methods, to find whether a method block contains at least one intercepted usage.
	/// If so, such method will be replaced with cached method.
	/// The requirement is that, the callee method should be applied with '<c>[InterceptorMethodCaller]</c>'.
	/// </remarks>
	public void Initialize(IncrementalGeneratorInitializationContext context)
		=> context.RegisterSourceOutput(
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					InterceptorMethodCallerAttributeTypeFullName,
					static (node, _) => node is MethodDeclarationSyntax,
					Transform
				)
				.Where(static data => data is not null)
				.Select(static (data, _) => data!)
				.Collect(),
			Output
		);


	private static void Output(SourceProductionContext spc, ImmutableArray<TransformResult> transformResults)
	{
		var failed = new List<FailedTransformResult>();
		var success = new List<SuccessTransformResult>();
		foreach (var result in transformResults)
		{
			Action r = result switch
			{
				FailedTransformResult f => () => failed.Add(f),
				SuccessTransformResult s => () => success.Add(s),
				AggregateSuccessTransformResult a => () => success.AddRange(a)
			};
			r();
		}
		failed.ForEach(f => spc.ReportDiagnostic(f.Diagnostic));
		if (failed.Count != 0)
		{
			return;
		}

		var list = new List<string>();
		foreach (var resultGroup in from result in success group result by result.Text)
		{
			// Replace all with new values.
			var attribute = new List<string>();
			foreach (var (_, (filePath, lineNumber, characterNumber)) in resultGroup)
			{
				attribute.Add($""""[global::{InterceptsLocationAttributeFullName}("""{filePath}""", {lineNumber}, {characterNumber})]"""");
			}
			list.Add(resultGroup.Key.Replace(AttributeInsertionMatchString, string.Join("\r\n\t", attribute)));
		}

		spc.AddSource("InterceptsLocationAttribute.cs", InterceptsLocationAttributeSourceCode);
		spc.AddSource(
			"Intercepted.g.cs",
			$$"""
			{{Banner.AutoGenerated}}

			#nullable enable
			#pragma warning disable

			namespace {{GeneratedNamespace}};
			
			{{string.Join("\r\n\r\n", list)}}
			"""
		);
	}

	private static TransformResult? Transform(GeneratorAttributeSyntaxContext gasc, CancellationToken ct)
	{
#if DEBUG
		if (!System.Diagnostics.Debugger.IsAttached)
		{
			System.Diagnostics.Debugger.Launch();
		}
#endif

		if (gasc is not
			{
				Attributes: _,
				TargetNode: MethodDeclarationSyntax
				{
					ExpressionBody: var expressionBody,
					Identifier: { ValueText: var methodName } identifierToken,
					//ConstraintClauses: var constraints
				} node,
				TargetSymbol: IMethodSymbol currentMethodSymbol,
				SemanticModel: { Compilation: var compilation } semanticModel
			})
		{
			return null;
		}

		var interceptorInstanceTypesAttributeSymbol = compilation.GetTypeByMetadataName(InterceptorInstanceTypesAttributeTypeFullName);
		if (interceptorInstanceTypesAttributeSymbol is null)
		{
			return Diagnostic.Create(Descriptor_Interceptor0100, null, messageArgs: [InterceptorInstanceTypesAttributeTypeFullName]);
		}

		var cachedAttributeSymbol = compilation.GetTypeByMetadataName(CachedAttributeTypeFullName);
		if (cachedAttributeSymbol is null)
		{
			return Diagnostic.Create(Descriptor_Interceptor0100, null, messageArgs: [CachedAttributeTypeFullName]);
		}

		if (expressionBody is not null)
		{
			return Diagnostic.Create(Descriptor_Interceptor0101, node.GetLocation(), messageArgs: [methodName]);
		}

		// Iterate on each invocation expression syntax node, to find any referenced methods marked '[Cached]' attribute.
		foreach (var invocation in node.DescendantNodes().OfType<InvocationExpressionSyntax>())
		{
			var (invocationLocation, referencedMethodDeclaration, referencedMethodSymbol) = default((Location, MethodDeclarationSyntax, IMethodSymbol));
			var invocationExpression = invocation.Expression;
			switch (semanticModel.GetSymbolInfo(invocation, ct))
			{
				case { CandidateSymbols: [IMethodSymbol { DeclaringSyntaxReferences: var syntaxRefs } methodSymbol] }
				when methodSymbol.GetAttributes().Any(cachedAttributeChecker):
				{
					if (syntaxRefs is not [var syntaxRef])
					{
						return Diagnostic.Create(
							Descriptor_Interceptor0103,
							Location.Create(syntaxRefs[0].SyntaxTree, syntaxRefs[0].Span),
							messageArgs: [invocationExpression.ToString()]
						);
					}

					invocationLocation = (invocationExpression as MemberAccessExpressionSyntax)?.Name.GetLocation();
					referencedMethodDeclaration = syntaxRef.GetSyntax(ct) as MethodDeclarationSyntax;
					referencedMethodSymbol = methodSymbol;
					break;
				}
				case { Symbol: IMethodSymbol { DeclaringSyntaxReferences: var syntaxRefs } methodSymbol }
				when methodSymbol.GetAttributes().Any(cachedAttributeChecker):
				{
					if (syntaxRefs is not [var syntaxRef])
					{
						return Diagnostic.Create(
							Descriptor_Interceptor0103,
							Location.Create(syntaxRefs[0].SyntaxTree, syntaxRefs[0].Span),
							messageArgs: [invocationExpression.ToString()]
						);
					}

					invocationLocation = (invocationExpression as MemberAccessExpressionSyntax)?.Name.GetLocation();
					referencedMethodDeclaration = syntaxRef.GetSyntax(ct) as MethodDeclarationSyntax;
					referencedMethodSymbol = methodSymbol;
					break;
				}
			}

#pragma warning disable format
			if ((invocationLocation, referencedMethodDeclaration, referencedMethodSymbol) is not (
				{ SourceTree.FilePath: var filePath },
				not null,
				{
					ReturnType: var referencedMethodReturnType,
					Parameters: var referencedMethodParameters
				}
			))
#pragma warning restore format
			{
				continue;
			}

			if (referencedMethodSymbol.IsGenericMethod)
			{
				return Diagnostic.Create(
					Descriptor_Interceptor0107,
					invocationLocation,
					messageArgs: [referencedMethodSymbol.Name]
				);
			}

			if (referencedMethodDeclaration.Body is not { Statements: var bodyStatements })
			{
				return Diagnostic.Create(
					Descriptor_Interceptor0101,
					invocationLocation,
					messageArgs: [referencedMethodSymbol.Name]
				);
			}

			// Now we have the referenced method data.
			// We should determine whether the method is block-bodied, and remove variable declarations
			// bound with cached-related properties, and append attributes [InterceptsLocation], emitting referenced locations.
			// However, here we cannot collect for all possible usages of [InterceptsLocation], so it will be postponed to be checked.
			var statements = new List<StatementSyntax>();
			var flag = false;
			var (existsBeginComment, existsEndComment) = (false, false);
			var duplicateBeginCommentOrEndComment = false;
			foreach (var statement in bodyStatements)
			{
				if (statement.HasLeadingTrivia)
				{
					var leadingTrivia = statement.GetLeadingTrivia().ToFullString();
					if (leadingTrivia.Contains(CommentLineBegin))
					{
						flag = true;
						if (!existsBeginComment)
						{
							existsBeginComment = true;
						}
						else
						{
							duplicateBeginCommentOrEndComment = true;
							break;
						}
						continue;
					}
					if (leadingTrivia.Contains(CommentLineEnd))
					{
						// Get leading trivia, and only removes special line.
						var otherLines = new List<string>();
						foreach (var triviaLine in leadingTrivia.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries))
						{
							if (!triviaLine.Contains(CommentLineEnd))
							{
								otherLines.Add(triviaLine);
							}
						}

						statements.Add(
							statement
								.WithoutLeadingTrivia()
								.WithLeadingTrivia(SyntaxFactory.ParseLeadingTrivia(string.Join("\r\n", otherLines)))
						);
						flag = false;
						if (!existsEndComment)
						{
							existsEndComment = true;
						}
						else
						{
							duplicateBeginCommentOrEndComment = true;
							break;
						}
						continue;
					}
				}
				if (!flag)
				{
					statements.Add(statement);
				}
			}
			if (duplicateBeginCommentOrEndComment)
			{
				return Diagnostic.Create(
					Descriptor_Interceptor0105,
					identifierToken.GetLocation(),
					messageArgs: [identifierToken.ValueText]
				);
			}
			if (!existsBeginComment || !existsEndComment)
			{
				return Diagnostic.Create(
					Descriptor_Interceptor0104,
					identifierToken.GetLocation(),
					messageArgs: [identifierToken.ValueText]
				);
			}

			//var genericTypesString = referencedMethodSymbol.IsGenericMethod
			//	&& (from typeParameter in referencedMethodSymbol.TypeParameters select typeParameter.ToDisplayString()) is var p
			//	&& string.Join(", ", p) is var typeParametersString
			//	? $"<{typeParametersString}>"
			//	: string.Empty;

			var ((startLine, startCharacter), _) = invocationLocation.GetMappedLineSpan();
			var parametersString = string.Join(
				", ",
				from parameter in referencedMethodParameters
				let refKindString = parameter.RefKind switch
				{
					RefKind.Ref => "ref ",
					RefKind.Out => "out ",
					RefKind.In => "in ",
					RefKind.RefReadOnlyParameter => "ref readonly ",
					_ => string.Empty
				}
				let scopedKindString = parameter.ScopedKind switch
				{
					ScopedKind.ScopedRef or ScopedKind.ScopedValue => "scoped ",
					_ => string.Empty
				}
				let typeNameString = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
				let defaultValue = parameter.HasExplicitDefaultValue
					? parameter.ExplicitDefaultValue switch
					{
						null => "default",
						string and [.. var s, '"']
							=> $""""
							"""
							{s}"
							"""
							"""",
						string s
							=> $""""
							"""{s}"""
							"""",
						char c => $"'{c}'",
						var value => value.ToString()
					}
					: null
				let defaultValueString = defaultValue is null ? string.Empty : $" = {defaultValue}"
				select $"{scopedKindString}{refKindString}{typeNameString} {parameter.Name}{defaultValueString}"
			);

			// Replace reserved identifiers with cached properties.
			var targetString = string.Join("\r\n", from statement in statements select statement.ToFullString());
			foreach (var variableName in ValidVariableNames)
			{
				targetString = targetString.Replace(variableName, variableName[2..]);
			}

			// Add one extra indenting.
			var targetStringAppendIndenting = new List<string>();
			foreach (var line in targetString.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries))
			{
				targetStringAppendIndenting.Add(line);
			}

			// Get XML doc comments.
			// The target XML doc commment structure won't include triple slashes. We should append them;
			// In addition, consider indenting, we should append indenting \t's.
			// And, we should remove the first and last line (<member> tag).
			var xmlDocCommentsSplitByLine = referencedMethodSymbol.GetDocumentationCommentXml(cancellationToken: ct)?
				.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries);
			var xmlDocCommentLines = new List<string>();
			if (xmlDocCommentsSplitByLine is not null)
			{
				for (var i = 1; i < xmlDocCommentsSplitByLine.Length - 1; i++)
				{
					xmlDocCommentLines.Add($"/// {xmlDocCommentsSplitByLine[i].TrimStart()}");
				}
			}

			// Return type.
			var returnTypeName = referencedMethodReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			var returnRefKindType = referencedMethodSymbol switch
			{
				{ ReturnsByRefReadonly: true } => "ref readonly ",
				{ ReturnsByRef: true } => "ref ",
				_ => string.Empty
			};
			var returnTypeString = $"{returnRefKindType}{returnTypeName}";

			//var constraintsString = constraints.Count != 0 ? constraints.ToString() : string.Empty;

			// XML documentation comments.
			var xmlDocComments = xmlDocCommentLines.Count == 0
				? """
					/// <summary>
					/// Intercepted method.
					/// </summary>
				"""
				: string.Join("\r\n\t", xmlDocCommentLines);

			// If the referenced method is an instance method instead of a static method,
			// we should consider inserting an extra parameter as instance member accessing.
			var instanceParameter = string.Empty;
			if (referencedMethodSymbol is { IsStatic: false, ContainingType: { IsRefLikeType: var isRefStruct } containingType })
			{
				var scopedKeyword = isRefStruct ? "scoped " : string.Empty;
				var containingTypeString = containingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				instanceParameter = $"this {scopedKeyword}{containingTypeString} @this, ";

				// Check whether the referenced method declaration has instance member accessing.
				// If so, we should replace them with '@this.' invocation (or disallow now).
				var hasThisMemberAccessing = false;
				foreach (var tempNode in referencedMethodDeclaration.DescendantNodes().OfType<MemberAccessExpressionSyntax>())
				{
					// Detect 'this.' references has two cases:
					//   1) this.Member
					//   2) Member, with 'Member' is an instance member in the current type 'containingType'
					// By check its operation, we can know which kind of the reference it is.
					switch (semanticModel.GetOperation(tempNode, ct))
					{
						// 1) this.Member or base.Member
						case IInstanceReferenceOperation { ReferenceKind: InstanceReferenceKind.ContainingTypeInstance }:
						// 2) Member
						case IMemberReferenceOperation { Member: { IsStatic: false, ContainingType: var memberContaingType } }
						when SymbolEqualityComparer.Default.Equals(memberContaingType, containingType):
						{
							hasThisMemberAccessing = true;
							goto CheckThisOrBaseExpression;
						}
					}
				}

			CheckThisOrBaseExpression:
				if (hasThisMemberAccessing)
				{
					// Today I won't handle this because it is too complex to be checked...
					// I'll implement a 'SyntaxRewriter' to replace nodes, to change this code.
					return Diagnostic.Create(Descriptor_Interceptor0106, identifierToken.GetLocation(), messageArgs: null);
				}
			}

			// Check whether the method marked '[InterceptorMethodCaller]' is also marked '[InterceptorInstanceTypes]'.
			// If so, we should generate an extra entry method to route functions by checking the target type
			// of this parameter '@this'.
			//var attributesMarked = currentMethodSymbol.GetAttributes();
			//var instanceTypesAttributeMarked = attributesMarked.FirstOrDefault(interceptorInstanceTypesAttributeChecker);
			//if (instanceTypesAttributeMarked is { ConstructorArguments: [{ Values: var instanceTypesRawValue }] })
			//{
			//	var instanceTypes = (
			//		from i in instanceTypesRawValue
			//		let targetType = i.Type as INamedTypeSymbol
			//		where targetType is not null
			//		select targetType into targetType
			//		let targetTypeString = targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
			//		select (Type: targetType, TypeString: targetTypeString)
			//	).ToArray();
			//
			//	var switchStatementOrExpressionString = referencedMethodReturnType.SpecialType == SpecialType.System_Void
			//		? ""
			//		: "";
			//	var entryMethodString =
			//		$$"""
			//			/// <summary>
			//			/// The backing entry that can route functions
			//			/// by checking the target type of instance parameter <paramref cref="this"/>.
			//			/// </summary>
			//			private static {{returnTypeString}} {{referencedMethodSymbol.Name}}_SwitchEntry({{instanceParameter}}{{parametersString}})
			//			{
			//		{{switchStatementOrExpressionString}}
			//			}
			//		""";
			//
			//	var instanceTypesGeneratedResult = new List<SuccessTransformResult>();
			//	foreach (var (instanceType, instanceTypeString) in instanceTypes)
			//	{
			//		var referencedMethodSymbol_a = instanceType.GetMembers().FirstOrDefault(referencedMethodSymbolChecker);
			//		if (referencedMethodSymbol_a is not
			//			{
			//				ContainingType.Name: var referencedMethodContainingTypeName_a,
			//				DeclaringSyntaxReferences: [var syntaxRef],
			//				Name: var referencedMethodName_a
			//			})
			//		{
			//			continue;
			//		}
			//
			//		var invocationLocation_a = (invocationExpression as MemberAccessExpressionSyntax)?.Name.GetLocation();
			//		var referencedMethodDeclaration_a = syntaxRef.GetSyntax(ct) as MethodDeclarationSyntax;
			//		//instanceTypesGeneratedResult.Add(
			//		//	new(
			//		//		$$"""
			//		//		/// <summary>
			//		//		/// Interceptor method that will replace implementation on such referenced method invocation.
			//		//		/// </summary>
			//		//		public static class {{referencedMethodContainingTypeName_a}}_Intercepted
			//		//		{
			//		//			{{xmlDocComments}}
			//		//			{{AttributeInsertionMatchString}}
			//		//			public static {{returnTypeString}} {{referencedMethodName_a}}({{instanceParameter}}{{parametersString}})
			//		//			{
			//		//				{{string.Join("\r\n", targetStringAppendIndenting)}}
			//		//			}
			//		//		}
			//		//		""",
			//		//
			//		//		// Here we should manually add 1 because line number starts with 1 instead of 0.
			//		//		new(filePath, startLine + 1, startCharacter + 1)
			//		//	)
			//		//);
			//	}
			//	return instanceTypesGeneratedResult.ToArray();
			//}

			// Return the value (not aggregate).
			return new SuccessTransformResult(
				$$"""
				/// <summary>
				/// Interceptor method that will replace implementation on such referenced method invocation.
				/// </summary>
				public static class {{referencedMethodSymbol.ContainingType.Name}}_Intercepted
				{
					{{xmlDocComments}}
					{{AttributeInsertionMatchString}}
					public static {{returnTypeString}} {{referencedMethodSymbol.Name}}({{instanceParameter}}{{parametersString}})
					{
				{{string.Join("\r\n", targetStringAppendIndenting)}}
					}
				}
				""",

				// Here we should manually add 1 because line number starts with 1 instead of 0.
				new(filePath, startLine + 1, startCharacter + 1)
			);


			//bool referencedMethodSymbolChecker(ISymbol member)
			//	=> member is IMethodSymbol && member.Name == referencedMethodSymbol.Name && member.IsOverride;
		}

		return Diagnostic.Create(Descriptor_Interceptor0102, identifierToken.GetLocation(), messageArgs: [identifierToken.ValueText]);


		bool cachedAttributeChecker(AttributeData a)
			=> SymbolEqualityComparer.Default.Equals(a.AttributeClass, cachedAttributeSymbol);

		//bool interceptorInstanceTypesAttributeChecker(AttributeData a)
		//	=> SymbolEqualityComparer.Default.Equals(a.AttributeClass, interceptorInstanceTypesAttributeSymbol);
	}
}
