//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.CommandLine.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.CommandLine.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the address of the bot to be connected to. Generally the value is &apos;localhost:8080&apos;..
        /// </summary>
        internal static string _Description_Address_Bot {
            get {
                return ResourceManager.GetString("_Description_Address_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To launch bot procedure..
        /// </summary>
        internal static string _Description_Bot {
            get {
                return ResourceManager.GetString("_Description_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the real number of the bot..
        /// </summary>
        internal static string _Description_BotNumber_Bot {
            get {
                return ResourceManager.GetString("_Description_BotNumber_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To check the attributes for a sudoku grid..
        /// </summary>
        internal static string _Description_Check {
            get {
                return ResourceManager.GetString("_Description_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates what kind of attribute will be checked..
        /// </summary>
        internal static string _Description_CheckType_Check {
            get {
                return ResourceManager.GetString("_Description_CheckType_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a sudoku grid onto a picture..
        /// </summary>
        internal static string _Description_Draw {
            get {
                return ResourceManager.GetString("_Description_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the extra footer text displayed below the picture..
        /// </summary>
        internal static string _Description_FooterText_Draw {
            get {
                return ResourceManager.GetString("_Description_FooterText_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To format a sudoku grid using string as the result representation..
        /// </summary>
        internal static string _Description_Format {
            get {
                return ResourceManager.GetString("_Description_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the format string used..
        /// </summary>
        internal static string _Description_FormatString_Format {
            get {
                return ResourceManager.GetString("_Description_FormatString_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate a sudoku puzzle..
        /// </summary>
        internal static string _Description_Generate {
            get {
                return ResourceManager.GetString("_Description_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method that defines what algorithm used for generating a sudoku puzzle..
        /// </summary>
        internal static string _Description_GenerateType_Generate {
            get {
                return ResourceManager.GetString("_Description_GenerateType_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the sudoku grid as string representation..
        /// </summary>
        internal static string _Description_Grid_Check {
            get {
                return ResourceManager.GetString("_Description_Grid_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the sudoku grid as string representation..
        /// </summary>
        internal static string _Description_Grid_Draw {
            get {
                return ResourceManager.GetString("_Description_Grid_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the grid to be formatted..
        /// </summary>
        internal static string _Description_Grid_Format {
            get {
                return ResourceManager.GetString("_Description_Grid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the grid used for being solved..
        /// </summary>
        internal static string _Description_Grid_Solve {
            get {
                return ResourceManager.GetString("_Description_Grid_Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays all possible root commands provided..
        /// </summary>
        internal static string _Description_Help {
            get {
                return ResourceManager.GetString("_Description_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the type name whose corresponding command introduction is what you want to see..
        /// </summary>
        internal static string _Description_HelpCommandName_Help {
            get {
                return ResourceManager.GetString("_Description_HelpCommandName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the output path..
        /// </summary>
        internal static string _Description_OutputPath_Draw {
            get {
                return ResourceManager.GetString("_Description_OutputPath_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the blank between the grid lines and the picture border..
        /// </summary>
        internal static string _Description_OutsideOffset_Draw {
            get {
                return ResourceManager.GetString("_Description_OutsideOffset_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range of given cells that generated puzzle should be..
        /// </summary>
        internal static string _Description_Range_Generate {
            get {
                return ResourceManager.GetString("_Description_Range_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the size of the picture..
        /// </summary>
        internal static string _Description_Size_Draw {
            get {
                return ResourceManager.GetString("_Description_Size_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To solve a sudoku grid using the specified algorithm..
        /// </summary>
        internal static string _Description_Solve {
            get {
                return ResourceManager.GetString("_Description_Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the method to be used for solving a sudoku..
        /// </summary>
        internal static string _Description_SolveMethod_Solve {
            get {
                return ResourceManager.GetString("_Description_SolveMethod_Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the verify key used for making communication of web socket..
        /// </summary>
        internal static string _Description_VerifyKey_Bot {
            get {
                return ResourceManager.GetString("_Description_VerifyKey_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the version of the current command line project..
        /// </summary>
        internal static string _Description_Version {
            get {
                return ResourceManager.GetString("_Description_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To fetch the author or the repository link..
        /// </summary>
        internal static string _Description_Visit {
            get {
                return ResourceManager.GetString("_Description_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the link that outputs..
        /// </summary>
        internal static string _Description_VisitLink_Visit {
            get {
                return ResourceManager.GetString("_Description_VisitLink_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle: &apos;{0}&apos;
        ///Method name used: &apos;{1}&apos;
        ///---
        ///Solution: {2}
        ///Solving details:
        ///{3}.
        /// </summary>
        internal static string _MessageFormat_AnalysisResult {
            get {
                return ResourceManager.GetString("_MessageFormat_AnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , required.
        /// </summary>
        internal static string _MessageFormat_AndIsRequired {
            get {
                return ResourceManager.GetString("_MessageFormat_AndIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle: &apos;{0}&apos;
        ///The puzzle {1} a unique solution..
        /// </summary>
        internal static string _MessageFormat_CheckValidityResult {
            get {
                return ResourceManager.GetString("_MessageFormat_CheckValidityResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands:.
        /// </summary>
        internal static string _MessageFormat_CommandsAre {
            get {
                return ResourceManager.GetString("_MessageFormat_CommandsAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doesn&apos;t have.
        /// </summary>
        internal static string _MessageFormat_DoesNotHave {
            get {
                return ResourceManager.GetString("_MessageFormat_DoesNotHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid: &apos;{0}&apos;
        ///Format: &apos;{1}&apos;
        ///Result: {2}.
        /// </summary>
        internal static string _MessageFormat_FormatResult {
            get {
                return ResourceManager.GetString("_MessageFormat_FormatResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The puzzle generated: &apos;{0}&apos;..
        /// </summary>
        internal static string _MessageFormat_GeneratedPuzzleIs {
            get {
                return ResourceManager.GetString("_MessageFormat_GeneratedPuzzleIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has.
        /// </summary>
        internal static string _MessageFormat_Has {
            get {
                return ResourceManager.GetString("_MessageFormat_Has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success. Please visit the path &apos;{0}&apos; to view the file..
        /// </summary>
        internal static string _MessageFormat_OutputSuccess {
            get {
                return ResourceManager.GetString("_MessageFormat_OutputSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit the following site to learn more information..
        /// </summary>
        internal static string _MessageFormat_PleaseVisitFollowingLink {
            get {
                return ResourceManager.GetString("_MessageFormat_PleaseVisitFollowingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string _MessageFormat_Project {
            get {
                return ResourceManager.GetString("_MessageFormat_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root commands:.
        /// </summary>
        internal static string _MessageFormat_RootCommandsAre {
            get {
                return ResourceManager.GetString("_MessageFormat_RootCommandsAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle: &apos;{0}&apos;
        ///Method name used: &apos;{1}&apos;{2}
        ///---
        ///Solution: {3}.
        /// </summary>
        internal static string _MessageFormat_SolveResult {
            get {
                return ResourceManager.GetString("_MessageFormat_SolveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax &amp; Usage:.
        /// </summary>
        internal static string _MessageFormat_SyntaxAndUsageIs {
            get {
                return ResourceManager.GetString("_MessageFormat_SyntaxAndUsageIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL link:.
        /// </summary>
        internal static string _MessageFormat_UriLinkIs {
            get {
                return ResourceManager.GetString("_MessageFormat_UriLinkIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string _MessageFormat_Version {
            get {
                return ResourceManager.GetString("_MessageFormat_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to connect server of platform Mirai, with target bot number 1357924680, connection is localhost with port 8080, and verify key is &quot;HelloWorld&quot;..
        /// </summary>
        internal static string _Usage_Bot_1 {
            get {
                return ResourceManager.GetString("_Usage_Bot_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To check the validity of the specified sudoku grid..
        /// </summary>
        internal static string _Usage_Check_1 {
            get {
                return ResourceManager.GetString("_Usage_Check_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a grid onto a picture, with specified size 1000 and outside blank (pixels) 10, then output the picture to the local path to user&apos;s desktop, and output file name is &quot;output.png&quot;..
        /// </summary>
        internal static string _Usage_Draw_1 {
            get {
                return ResourceManager.GetString("_Usage_Draw_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats the specified grid, using the string &quot;0&quot; as the format one, which means the grid only displays the given cells, modifiables are treated as the empty ones, and all empty cells will be displayed as a zero character &apos;0&apos;..
        /// </summary>
        internal static string _Usage_Format_1 {
            get {
                return ResourceManager.GetString("_Usage_Format_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a sudoku puzzle, which contains givens of number between 24 and 30, and using the hard-pattern algorithm to generate puzzle..
        /// </summary>
        internal static string _Usage_Generate_1 {
            get {
                return ResourceManager.GetString("_Usage_Generate_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solves a sudoku puzzle, using the bitwise algorithm..
        /// </summary>
        internal static string _Usage_Solve_1 {
            get {
                return ResourceManager.GetString("_Usage_Solve_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits the GitHub link of the author..
        /// </summary>
        internal static string _Usage_Visit_1 {
            get {
                return ResourceManager.GetString("_Usage_Visit_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 924849321.
        /// </summary>
        internal static string SudokuGroupQQ {
            get {
                return ResourceManager.GetString("SudokuGroupQQ", resourceCulture);
            }
        }
    }
}
