//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block {0}.
        /// </summary>
        internal static string BlockLabel {
            get {
                return ResourceManager.GetString("BlockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, digit {1}.
        /// </summary>
        internal static string CandidateLabel {
            get {
                return ResourceManager.GetString("CandidateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row {0} column {1}.
        /// </summary>
        internal static string CellLabel {
            get {
                return ResourceManager.GetString("CellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cells: {0}.
        /// </summary>
        internal static string CellsLabel {
            get {
                return ResourceManager.GetString("CellsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0}.
        /// </summary>
        internal static string ColumnLabel {
            get {
                return ResourceManager.GetString("ColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} conjugates with {1}, for digit {2}.
        /// </summary>
        internal static string ConjugatePairWith {
            get {
                return ResourceManager.GetString("ConjugatePairWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit.
        /// </summary>
        internal static string DigitName {
            get {
                return ResourceManager.GetString("DigitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument should contains the prefix period token..
        /// </summary>
        internal static string Error_ArgExtensionShouldBeValid {
            get {
                return ResourceManager.GetString("Error_ArgExtensionShouldBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot append text that cannot be recognized as a valid sudoku grid..
        /// </summary>
        internal static string Error_UnrecognizedGridFormat {
            get {
                return ResourceManager.GetString("Error_UnrecognizedGridFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cells must be connected with adjacent positions. For example, r1c1 and r1c2 is a valid pair, but r1c1 and r2c2 is not..
        /// </summary>
        internal static string ErrorInfo_AllCellsMustBeConnectedWithAdjacentPositions {
            get {
                return ResourceManager.GetString("ErrorInfo_AllCellsMustBeConnectedWithAdjacentPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign success field to describe such failure..
        /// </summary>
        internal static string ErrorInfo_CannotAssignSuccessForFailureCases {
            get {
                return ResourceManager.GetString("ErrorInfo_CannotAssignSuccessForFailureCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two cells must be in a same line (row or column)..
        /// </summary>
        internal static string ErrorInfo_CellsShouldInSameLine {
            get {
                return ResourceManager.GetString("ErrorInfo_CellsShouldInSameLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The puzzle can be comparable if it must be a standard sudoku..
        /// </summary>
        internal static string ErrorInfo_ComparableGridMustBeStandard {
            get {
                return ResourceManager.GetString("ErrorInfo_ComparableGridMustBeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string contains empty segment..
        /// </summary>
        internal static string ErrorInfo_ContainsEmptySegmentOnParsing {
            get {
                return ResourceManager.GetString("ErrorInfo_ContainsEmptySegmentOnParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different existence of config file and library file..
        /// </summary>
        internal static string ErrorInfo_DifferentExistenceOfConfigAndLibraryFile {
            get {
                return ResourceManager.GetString("ErrorInfo_DifferentExistenceOfConfigAndLibraryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated or invalid values found..
        /// </summary>
        internal static string ErrorInfo_DuplicatedValuesMayExistOrInvalid {
            get {
                return ResourceManager.GetString("ErrorInfo_DuplicatedValuesMayExistOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related files should be initialized first..
        /// </summary>
        internal static string ErrorInfo_FileShouldBeInitializedFirst {
            get {
                return ResourceManager.GetString("ErrorInfo_FileShouldBeInitializedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grid is invalid - it may contain invalid internal data, or it is invalid as an argument to the method..
        /// </summary>
        internal static string ErrorInfo_GridInvalid {
            get {
                return ResourceManager.GetString("ErrorInfo_GridInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grid cannot keep invalid cell state value..
        /// </summary>
        internal static string ErrorInfo_GridInvalidCellState {
            get {
                return ResourceManager.GetString("ErrorInfo_GridInvalidCellState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grid contains multiple solutions..
        /// </summary>
        internal static string ErrorInfo_GridMultipleSolutions {
            get {
                return ResourceManager.GetString("ErrorInfo_GridMultipleSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grid has no possible solution..
        /// </summary>
        internal static string ErrorInfo_GridNoSolution {
            get {
                return ResourceManager.GetString("ErrorInfo_GridNoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state on parsing values..
        /// </summary>
        internal static string ErrorInfo_InvalidStateOnParsing {
            get {
                return ResourceManager.GetString("ErrorInfo_InvalidStateOnParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the string must be {0}..
        /// </summary>
        internal static string ErrorInfo_LengthMustBeMatched {
            get {
                return ResourceManager.GetString("ErrorInfo_LengthMustBeMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library is not initialized. It must be initialized file, ensuring the file in local exists..
        /// </summary>
        internal static string ErrorInfo_LibraryShouldBeInitialized {
            get {
                return ResourceManager.GetString("ErrorInfo_LibraryShouldBeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The puzzle should be standard sudoku puzzle, and contain a unique solution..
        /// </summary>
        internal static string ErrorInfo_MinLexShouldBeUniqueAndNotSukaku {
            get {
                return ResourceManager.GetString("ErrorInfo_MinLexShouldBeUniqueAndNotSukaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple chute values found..
        /// </summary>
        internal static string ErrorInfo_MultipleChuteValuesFound {
            get {
                return ResourceManager.GetString("ErrorInfo_MultipleChuteValuesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple conjuagte pair values found..
        /// </summary>
        internal static string ErrorInfo_MultipleConjugatePairValuesFound {
            get {
                return ResourceManager.GetString("ErrorInfo_MultipleConjugatePairValuesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple flags exist. The method only allows the enumeration field only holds one flag value..
        /// </summary>
        internal static string ErrorInfo_MultipleFlagsExist {
            get {
                return ResourceManager.GetString("ErrorInfo_MultipleFlagsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple same properties are found..
        /// </summary>
        internal static string ErrorInfo_MultipleSamePropertiesFound {
            get {
                return ResourceManager.GetString("ErrorInfo_MultipleSamePropertiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No possible elements can be found in the current sequence..
        /// </summary>
        internal static string ErrorInfo_NoElementsInSequence {
            get {
                return ResourceManager.GetString("ErrorInfo_NoElementsInSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist..
        /// </summary>
        internal static string ErrorInfo_NotExist {
            get {
                return ResourceManager.GetString("ErrorInfo_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function does not support for Sukaku puzzles..
        /// </summary>
        internal static string ErrorInfo_NotSupportedForSukakuPuzzles {
            get {
                return ResourceManager.GetString("ErrorInfo_NotSupportedForSukakuPuzzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The placeholder character invalid; expected: &apos;0&apos; or &apos;.&apos;..
        /// </summary>
        internal static string ErrorInfo_PlaceholderMustBeZeroOrDot {
            get {
                return ResourceManager.GetString("ErrorInfo_PlaceholderMustBeZeroOrDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pointer cannot move..
        /// </summary>
        internal static string ErrorInfo_PointerCannotMove {
            get {
                return ResourceManager.GetString("ErrorInfo_PointerCannotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string value is invalid to be parsed..
        /// </summary>
        internal static string ErrorInfo_StringValueInvalidToBeParsed {
            get {
                return ResourceManager.GetString("ErrorInfo_StringValueInvalidToBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both cells count and subset size is too large, which may cause potential out of memory exception. This operator will throw this exception to calculate the result, in order to prevent any possible exceptions thrown..
        /// </summary>
        internal static string ErrorInfo_SubsetsExceeded {
            get {
                return ResourceManager.GetString("ErrorInfo_SubsetsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to houses: {0}.
        /// </summary>
        internal static string HousesLabel {
            get {
                return ResourceManager.GetString("HousesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string LockedCandidatesLabel {
            get {
                return ResourceManager.GetString("LockedCandidatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega column {0}.
        /// </summary>
        internal static string MegaColumnLabel {
            get {
                return ResourceManager.GetString("MegaColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega lines: {0}.
        /// </summary>
        internal static string MegaLinesLabel {
            get {
                return ResourceManager.GetString("MegaLinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega row {0}.
        /// </summary>
        internal static string MegaRowLabel {
            get {
                return ResourceManager.GetString("MegaRowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library (local path: &apos;{0}\{1}&apos;) has already been initialized..
        /// </summary>
        internal static string Message_LibraryInitializedException {
            get {
                return ResourceManager.GetString("Message_LibraryInitializedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The puzzle has multiple solutions..
        /// </summary>
        internal static string Message_MultipleSolutionException {
            get {
                return ResourceManager.GetString("Message_MultipleSolutionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}.
        /// </summary>
        internal static string RowLabel {
            get {
                return ResourceManager.GetString("RowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string RowName {
            get {
                return ResourceManager.GetString("RowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also, please note that the pixels are changed in higher DPIs. If your computer is set *1.5 scale, sudoku grid pane of 610 pixel size will be zoomed in to 915 pixels (610 * 1.5 = 915)..
        /// </summary>
        internal static string SettingsPage_GridSizeDescription2 {
            get {
                return ResourceManager.GetString("SettingsPage_GridSizeDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All symmetry.
        /// </summary>
        internal static string SymmetricType_All {
            get {
                return ResourceManager.GetString("SymmetricType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-diagonal.
        /// </summary>
        internal static string SymmetricType_AntiDiagonal {
            get {
                return ResourceManager.GetString("SymmetricType_AntiDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both axes.
        /// </summary>
        internal static string SymmetricType_AxisBoth {
            get {
                return ResourceManager.GetString("SymmetricType_AxisBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central.
        /// </summary>
        internal static string SymmetricType_Central {
            get {
                return ResourceManager.GetString("SymmetricType_Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal.
        /// </summary>
        internal static string SymmetricType_Diagonal {
            get {
                return ResourceManager.GetString("SymmetricType_Diagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both diagonals.
        /// </summary>
        internal static string SymmetricType_DiagonalBoth {
            get {
                return ResourceManager.GetString("SymmetricType_DiagonalBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symmetry.
        /// </summary>
        internal static string SymmetricType_None {
            get {
                return ResourceManager.GetString("SymmetricType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X axis.
        /// </summary>
        internal static string SymmetricType_XAxis {
            get {
                return ResourceManager.GetString("SymmetricType_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y axis.
        /// </summary>
        internal static string SymmetricType_YAxis {
            get {
                return ResourceManager.GetString("SymmetricType_YAxis", resourceCulture);
            }
        }
    }
}
