//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block {0}.
        /// </summary>
        internal static string BlockLabel {
            get {
                return ResourceManager.GetString("BlockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, digit {1}.
        /// </summary>
        internal static string CandidateLabel {
            get {
                return ResourceManager.GetString("CandidateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row {0} column {1}.
        /// </summary>
        internal static string CellLabel {
            get {
                return ResourceManager.GetString("CellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cells: {0}.
        /// </summary>
        internal static string CellsLabel {
            get {
                return ResourceManager.GetString("CellsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0}.
        /// </summary>
        internal static string ColumnLabel {
            get {
                return ResourceManager.GetString("ColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} conjugates with {1}, for digit {2}.
        /// </summary>
        internal static string ConjugatePairWith {
            get {
                return ResourceManager.GetString("ConjugatePairWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to houses: {0}.
        /// </summary>
        internal static string HousesLabel {
            get {
                return ResourceManager.GetString("HousesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string LockedCandidatesLabel {
            get {
                return ResourceManager.GetString("LockedCandidatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega column {0}.
        /// </summary>
        internal static string MegaColumnLabel {
            get {
                return ResourceManager.GetString("MegaColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega lines: {0}.
        /// </summary>
        internal static string MegaLinesLabel {
            get {
                return ResourceManager.GetString("MegaLinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega row {0}.
        /// </summary>
        internal static string MegaRowLabel {
            get {
                return ResourceManager.GetString("MegaRowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}.
        /// </summary>
        internal static string RowLabel {
            get {
                return ResourceManager.GetString("RowLabel", resourceCulture);
            }
        }
    }
}
