namespace Sudoku.Resources;

/// <summary>
/// Represents a easy way to fetch resource values using the specified key and culture information.
/// </summary>
public static class ResourceDictionary
{
	/// <summary>
	/// The default binding flags.
	/// </summary>
	private const BindingFlags DefaultBindingFlags = BindingFlags.NonPublic | BindingFlags.Static;


	/// <summary>
	/// Try to get resource via the key.
	/// </summary>
	/// <param name="resourceKey">The resource key.</param>
	/// <param name="culture">The culture.</param>
	/// <param name="assembly">The assembly storing the resource dictionaries.</param>
	/// <returns>The result string.</returns>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static string GetString(string resourceKey, CultureInfo? culture = null, Assembly? assembly = null)
		=> GetAssemblyResourceReader(assembly ?? Assembly.GetCallingAssembly())!.GetResource(resourceKey, culture);

	/// <summary>
	/// Try to fetch an instance for the resource dictionary for the specified assembly.
	/// The return type may be a <see cref="ResourceReader"/> object, because it is generated by compiler.
	/// </summary>
	/// <param name="this">The assembly instance.</param>
	/// <returns>A dynamic object that describes the resource dictionary.</returns>
	/// <exception cref="MissingResourceManagerException">
	/// Throws when the resource reader is not found, meaning the assembly doesn't store any resources.
	/// </exception>
	/// <seealso cref="ResourceReader"/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>")]
	private static IResourceReader GetAssemblyResourceReader(Assembly @this)
		=> @this.GetGenericAttributeTypeArguments(typeof(ResourceLocationAttribute<>)) switch
		{
			[var specifier] => specifier.GetProperty("ResourceManager", DefaultBindingFlags) switch
			{
				{ } pi => new EntryResourceReader((ResourceManager)pi.GetValue(null)!),
				_ => null
			},
			_ => null
		} ?? throw new MissingResourceManagerException(@this);
}

/// <summary>
/// The entry resource reader.
/// </summary>
/// <param name="resourceManager">The resource manager.</param>
file sealed class EntryResourceReader(ResourceManager resourceManager) : IResourceReader
{
	/// <inheritdoc/>
	ResourceManager IResourceReader.ResourceManager => resourceManager;
}
