global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using Microsoft.UI.Input;
global using Microsoft.UI.Windowing;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Markup;
global using Sudoku.UI.Interop;
global using Windows.System;
global using Windows.UI.Core;
global using WinRT;
global using WinRT.Interop;
global using static Sudoku.Resources.MergedResources;
global using GridLayout = Microsoft.UI.Xaml.Controls.Grid;
global using WinsysDispatcherQueue = Windows.System.DispatcherQueue;
global using WinsysDispatcherQueueController = Windows.System.DispatcherQueueController;
