global using System;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.Versioning;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using COSXML;
global using COSXML.Auth;
global using COSXML.Transfer;
global using MyBot.Api;
global using MyBot.Datas;
global using MyBot.Models.MessageModels;
global using Sudoku.Analytics;
global using Sudoku.Bot;
global using Sudoku.Bot.Commands;
global using Sudoku.Bot.Localization;
global using Sudoku.Bot.Logging;
global using Sudoku.Bot.Scoring;
global using Sudoku.Concepts;
global using Sudoku.Drawing.Drawing2D;
global using Sudoku.Runtime.CosServices;
global using static System.Math;
global using static Sudoku.Bot.Localization.CommonStrings;
global using static Sudoku.Bot.Logging.Console2;
global using Emoji = Sudoku.Bot.Localization.CommonStrings.Emoji;
global using FormattingOptions = Sudoku.Analytics.AnalysisResult.FormattingOptions;
global using QQGroupBot = MyBot.Expansions.Bot.ChannelBot;
global using SpecialFolder = System.Environment.SpecialFolder;
