[assembly: InternalsVisibleTo("Sudoku.Core.CodeGen")]
[assembly: InternalsVisibleTo("Sudoku.Diagnostics.CodeAnalysis")]
[assembly: InternalsVisibleTo("Sudoku.Diagnostics.CodeAnalysis.CodeGen")]
[assembly: InternalsVisibleTo("Sudoku.Diagnostics.CodeGen")]
[assembly: InternalsVisibleTo("SystemExtensions.CodeGen")]
