global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.CodeGen;
global using System.Linq;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Sudoku.Analytics;
global using Sudoku.Concepts;
global using Sudoku.Presentation.Nodes;
global using Sudoku.Presentation.Nodes.Grouped;
global using Sudoku.Presentation.Nodes.Shapes;
global using Sudoku.Text.Notations;
global using Sudoku.Text.Serialization;
global using static System.Text.Json.JsonSerializer;
global using static Sudoku.SolutionWideReadOnlyFields;
