global using System;
global using System.Buffers;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Sudoku.Concepts;
global using Sudoku.Presentation;
global using Sudoku.Presentation.Nodes;
global using Sudoku.Solving;
global using Sudoku.Text.Serialization.Specialized;
global using static System.Text.Json.JsonSerializer;
global using static Sudoku.SolutionWideReadOnlyFields;
