//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrategyingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrategyingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Resources.StrategyingResources", typeof(StrategyingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string _Token_Comma {
            get {
                return ResourceManager.GetString("_Token_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to both side closed.
        /// </summary>
        internal static string BothClosed {
            get {
                return ResourceManager.GetString("BothClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to both side open.
        /// </summary>
        internal static string BothOpen {
            get {
                return ResourceManager.GetString("BothOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclusion count rule: Conclusion {0} should {1}appear.
        /// </summary>
        internal static string ConclusionConstraint {
            get {
                return ResourceManager.GetString("ConclusionConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count between rule: {0} should be between {1} and {2}, {3}.
        /// </summary>
        internal static string CountBetweenConstraint {
            get {
                return ResourceManager.GetString("CountBetweenConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diamond.
        /// </summary>
        internal static string DiamondString {
            get {
                return ResourceManager.GetString("DiamondString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty level rule: {0} {1} ({2}).
        /// </summary>
        internal static string DifficultyLevelConstraint {
            get {
                return ResourceManager.GetString("DifficultyLevelConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of empty cells.
        /// </summary>
        internal static string EmptyCell {
            get {
                return ResourceManager.GetString("EmptyCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of given cells.
        /// </summary>
        internal static string GivenCell {
            get {
                return ResourceManager.GetString("GivenCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ittoryu rule: finish puzzle with {0} {1} rounds.
        /// </summary>
        internal static string IttoryuConstraint {
            get {
                return ResourceManager.GetString("IttoryuConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ittoryu length rule: {0} {1} consecutively-finished digits.
        /// </summary>
        internal static string IttoryuLengthConstraint {
            get {
                return ResourceManager.GetString("IttoryuLengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only left open.
        /// </summary>
        internal static string LeftOpen {
            get {
                return ResourceManager.GetString("LeftOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal rule: should {0}be a minimal puzzle.
        /// </summary>
        internal static string MinimalConstraint {
            get {
                return ResourceManager.GetString("MinimalConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not .
        /// </summary>
        internal static string NoString {
            get {
                return ResourceManager.GetString("NoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string NounPluralSuffix {
            get {
                return ResourceManager.GetString("NounPluralSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rule: should {1}be a {2} puzzle.
        /// </summary>
        internal static string PearlOrDiamondConstraint {
            get {
                return ResourceManager.GetString("PearlOrDiamondConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pearl.
        /// </summary>
        internal static string PearlString {
            get {
                return ResourceManager.GetString("PearlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only right open.
        /// </summary>
        internal static string RightOpen {
            get {
                return ResourceManager.GetString("RightOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry rule: {0}.
        /// </summary>
        internal static string SymmetryConstraint {
            get {
                return ResourceManager.GetString("SymmetryConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique rule: {0}.
        /// </summary>
        internal static string TechniqueConstraint {
            get {
                return ResourceManager.GetString("TechniqueConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique appearing times rule: {0} appears {1} {2} time(s).
        /// </summary>
        internal static string TechniqueCountConstraint {
            get {
                return ResourceManager.GetString("TechniqueCountConstraint", resourceCulture);
            }
        }
    }
}
