global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Linq;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Sudoku.Diagnostics.CodeGen;
global using static Sudoku.Diagnostics.CodeGen.Constants;
global using Kind = Microsoft.CodeAnalysis.TypeKind;
