using static Sudoku.Runtime.AnalysisServices.DisabledReason;
using static Sudoku.Runtime.AnalysisServices.DisplayingLevel;
using static Sudoku.Runtime.AnalysisServices.EnabledArea;

[assembly: SearcherConfiguration<SingleStepSearcher>(A)]
[assembly: SearcherConfiguration<LockedCandidatesStepSearcher>(A)]
[assembly: SearcherConfiguration<SubsetStepSearcher>(B)]
[assembly: SearcherConfiguration<NormalFishStepSearcher>(B)]
[assembly: SearcherConfiguration<TwoStrongLinksStepSearcher>(B)]
[assembly: SearcherConfiguration<RegularWingStepSearcher>(B)]
[assembly: SearcherConfiguration<WWingStepSearcher>(B)]
[assembly: SearcherConfiguration<UniqueRectangleStepSearcher>(B)]
[assembly: SearcherConfiguration<AlmostLockedCandidatesStepSearcher>(B)]
[assembly: SearcherConfiguration<SueDeCoqStepSearcher>(C)]
[assembly: SearcherConfiguration<SueDeCoq3DimensionStepSearcher>(B)]
[assembly: SearcherConfiguration<UniqueLoopStepSearcher>(B)]
[assembly: SearcherConfiguration<ExtendedRectangleStepSearcher>(B)]
[assembly: SearcherConfiguration<EmptyRectangleStepSearcher>(B)]
[assembly: SearcherConfiguration<UniqueSquareStepSearcher>(B)]
[assembly: SearcherConfiguration<UniquePolygonStepSearcher>(B)]
[assembly: SearcherConfiguration<QiuDeadlyPatternStepSearcher>(B)]
[assembly: SearcherConfiguration<BivalueUniversalGraveStepSearcher>(B)]
[assembly: SearcherConfiguration<EmptyRectangleIntersectionPairStepSearcher>(B)]
[assembly: SearcherConfiguration<FireworkStepSearcher>(B)]
[assembly: SearcherConfiguration<AlmostLockedSetsXzStepSearcher>(B)]
[assembly: SearcherConfiguration<AlmostLockedSetsXyWingStepSearcher>(B)]
[assembly: SearcherConfiguration<AlmostLockedSetsWWingStepSearcher>(B)]
[assembly: SearcherConfiguration<AlternatingInferenceChainStepSearcher>(B)]
[assembly: SearcherConfiguration<ComplexFishStepSearcher>(B)]
[assembly: SearcherConfiguration<GuardianStepSearcher>(B)]
[assembly: SearcherConfiguration<BivalueOddagonStepSearcher>(B)]
[assembly: SearcherConfiguration<ChromaticPatternStepSearcher>(B)]
[assembly: SearcherConfiguration<BowmanBingoStepSearcher>(C, EnabledArea = EnabledArea.None, DisabledReason = TooSlow | LastResort)]
[assembly: SearcherConfiguration<PatternOverlayStepSearcher>(C, EnabledArea = Gathering, DisabledReason = LastResort)]
[assembly: SearcherConfiguration<TemplateStepSearcher>(C, EnabledArea = EnabledArea.None, DisabledReason = LastResort)]
[assembly: SearcherConfiguration<JuniorExocetStepSearcher>(D)]
[assembly: SearcherConfiguration<SeniorExocetStepSearcher>(D, EnabledArea = EnabledArea.None, DisabledReason = DeprecatedOrNotImplemented)]
[assembly: SearcherConfiguration<DominoLoopStepSearcher>(D)]
[assembly: SearcherConfiguration<MultisectorLockedSetsStepSearcher>(D)]
[assembly: SearcherConfiguration<BruteForceStepSearcher>(DisplayingLevel.E, EnabledArea = Default, DisabledReason = LastResort)]
[module: SkipLocalsInit]
