[assembly: SearcherConfiguration<SingleStepSearcher>(1, DisplayingLevel.A)]
[assembly: SearcherConfiguration<LockedCandidatesStepSearcher>(2, DisplayingLevel.A)]
[assembly: SearcherConfiguration<SubsetStepSearcher>(3, DisplayingLevel.B)]
[assembly: SearcherConfiguration<NormalFishStepSearcher>(4, DisplayingLevel.B)]
[assembly: SearcherConfiguration<TwoStrongLinksStepSearcher>(5, DisplayingLevel.B)]
[assembly: SearcherConfiguration<RegularWingStepSearcher>(6, DisplayingLevel.B)]
[assembly: SearcherConfiguration<WWingStepSearcher>(7, DisplayingLevel.B)]
[assembly: SearcherConfiguration<UniqueRectangleStepSearcher>(8, DisplayingLevel.B)]
[assembly: SearcherConfiguration<AlmostLockedCandidatesStepSearcher>(9, DisplayingLevel.B)]
[assembly: SearcherConfiguration<UniqueLoopStepSearcher>(10, DisplayingLevel.B)]
[assembly: SearcherConfiguration<ExtendedRectangleStepSearcher>(11, DisplayingLevel.B)]
[assembly: SearcherConfiguration<EmptyRectangleStepSearcher>(12, DisplayingLevel.B)]
[assembly: SearcherConfiguration<SueDeCoqStepSearcher>(13, DisplayingLevel.C)]
[assembly: SearcherConfiguration<SueDeCoq3DimensionStepSearcher>(14, DisplayingLevel.B)]
[assembly: SearcherConfiguration<UniqueSquareStepSearcher>(15, DisplayingLevel.B)]
[assembly: SearcherConfiguration<UniquePolygonStepSearcher>(16, DisplayingLevel.B)]
[assembly: SearcherConfiguration<QiuDeadlyPatternStepSearcher>(17, DisplayingLevel.B)]
[assembly: SearcherConfiguration<BivalueUniversalGraveStepSearcher>(18, DisplayingLevel.B)]
[assembly: SearcherConfiguration<EmptyRectangleIntersectionPairStepSearcher>(19, DisplayingLevel.B)]
[assembly: SearcherConfiguration<AlternatingInferenceChainStepSearcher>(20, DisplayingLevel.B)]
[assembly: SearcherConfiguration<GuardianStepSearcher>(21, DisplayingLevel.B)]
[assembly: SearcherConfiguration<BivalueOddagonStepSearcher>(22, DisplayingLevel.B)]
[assembly: SearcherConfiguration<BowmanBingoStepSearcher>(23, DisplayingLevel.C, EnabledArea = EnabledArea.None, DisabledReason = DisabledReason.TooSlow | DisabledReason.LastResort)]
[assembly: SearcherConfiguration<PatternOverlayStepSearcher>(24, DisplayingLevel.C, EnabledArea = EnabledArea.Gathering, DisabledReason = DisabledReason.LastResort)]
[assembly: SearcherConfiguration<TemplateStepSearcher>(25, DisplayingLevel.C, EnabledArea = EnabledArea.None, DisabledReason = DisabledReason.LastResort)]
[assembly: SearcherConfiguration<AlmostLockedSetsXzStepSearcher>(26, DisplayingLevel.B)]
[assembly: SearcherConfiguration<AlmostLockedSetsXyWingStepSearcher>(27, DisplayingLevel.B)]
[assembly: SearcherConfiguration<AlmostLockedSetsWWingStepSearcher>(28, DisplayingLevel.B)]
[assembly: SearcherConfiguration<ComplexFishStepSearcher>(29, DisplayingLevel.B)]
[assembly: SearcherConfiguration<JuniorExocetStepSearcher>(30, DisplayingLevel.D, EnabledArea = EnabledArea.None, DisabledReason = DisabledReason.DeprecatedOrNotImplemented)]
[assembly: SearcherConfiguration<SeniorExocetStepSearcher>(31, DisplayingLevel.D, EnabledArea = EnabledArea.None, DisabledReason = DisabledReason.DeprecatedOrNotImplemented)]
[assembly: SearcherConfiguration<MultisectorLockedSetsStepSearcher>(32, DisplayingLevel.D)]
[assembly: SearcherConfiguration<DominoLoopStepSearcher>(33, DisplayingLevel.D)]
[assembly: SearcherConfiguration<BruteForceStepSearcher>(34, DisplayingLevel.E, EnabledArea = EnabledArea.Default, DisabledReason = DisabledReason.LastResort)]
[module: SkipLocalsInit]
