namespace System.Diagnostics.CodeAnalysis;

/// <summary>
/// <para>
/// Indicates the current constructor is a primary constructor in a normal <see langword="struct"/>
/// or <see langword="class"/>, which means the constructor is generated by the source generator,
/// and marks onto the constructor to distinct the generated constructor or the normal constructors.
/// </para>
/// <para>
/// Although the primary constructor is now only used for <see langword="record"/>s or
/// <see langword="record struct"/>s, this concept is nearly totally same as the primary constructors
/// in <see langword="record"/>s.
/// </para>
/// </summary>
[AttributeUsage(AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
public sealed class PrimaryConstructorAttribute : Attribute
{
}
