//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources2052 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources2052() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Resources.Resources2052", typeof(Resources2052).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出现.
        /// </summary>
        internal static string Appear {
            get {
                return ResourceManager.GetString("Appear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 守护者.
        /// </summary>
        internal static string GuardianPlural {
            get {
                return ResourceManager.GetString("GuardianPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 守护者.
        /// </summary>
        internal static string GuardianSingular {
            get {
                return ResourceManager.GetString("GuardianSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位于.
        /// </summary>
        internal static string KeywordIn {
            get {
                return ResourceManager.GetString("KeywordIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2052.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只.
        /// </summary>
        internal static string Only {
            get {
                return ResourceManager.GetString("Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  或 .
        /// </summary>
        internal static string OrKeywordWithSpaces {
            get {
                return ResourceManager.GetString("OrKeywordWithSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 从 {BaseCellsStr} 往 {TargetCellsStr} 推理 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlmostLockedCandidatesStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlmostLockedCandidatesStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：ALS {Als1Str} 和 {Als2Str} 以共轭对 {ConjStr} 关联起来；其中 W = {WStr}、X = {XStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlmostLockedSetsWWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlmostLockedSetsWWingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{Als1Str} -&gt; {BridgeStr} -&gt; {Als2Str}；其中 X = {XStr}、Y = {YStr}、Z = {ZStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlmostLockedSetsXyWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlmostLockedSetsXyWingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：ALS #1：{Als1Str}、ALS #2：{Als2Str}、X = {XStr}{ZResultStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlmostLockedSetsXzRule {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlmostLockedSetsXzRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：链 {ChainStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlternatingInferenceChainStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlternatingInferenceChainStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {D1Str} 和 {D2Str} 位于单元格 {CellsStr} 构成结构，并带排除法：如果单元格 {BaseCellStr} 填上了数字 {Digit1Str}，{RegionStr} 区域仅能让 {TargetCellStr} 填入该数字，便出现致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AvoidableRectangleWithHiddenSingleStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AvoidableRectangleWithHiddenSingleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：可以证明如果 {AnchorCandidateStr} 为{AnchorIsTrueOrFalseStr}时会产生矛盾 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BinaryChainingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BinaryChainingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果单元格 {CellStr} 只有数字 {Digit1Str} 和 {Digit2Str} 的话，整个环 {LoopStr} 会直接导致违背规则的矛盾现象 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueOddagonType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueOddagonType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果所有在单元格 {LoopStr} 里的数字 {ExtraDigitStr} 全部删掉，则整个环会直接导致违背规则的矛盾现象 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueOddagonType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueOddagonType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：为规避数字 {Digit1Str} 和 {Digit2Str} 在单元格 {LoopStr} 里出错，唯一的办法就是和 {ExtraCellsStr} 单元格组成关于数字 {DigitsStr} 的数组 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueOddagonType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueOddagonType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：真数为 {CandidatesStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveMultipleStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveMultipleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：单元格 {CellsStr} 里包含额外数字 {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：真数 {TrueCandidatesStr}，伴有{SubsetTypeStr}{SizeStrZhCn}于单元格 {CellsStr} 里，涉及数字 {ExtraDigitsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：位于单元格 {CellsStr} 里的数字 {DigitsStr}，带有一个共轭对 {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitStr} 位于单元格 {CellsStr} 里，并带有额外单元格 {ExtraCellStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveXzStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveXzStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：设 {ContradictionSeriesStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BowmanBingoStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BowmanBingoStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{AssignmentStr}.
        /// </summary>
        internal static string TechniqueFormat_BruteForceStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BruteForceStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：可以通过强制链来证明得到 {SourceCellStr} 里的所有候选数全部为假 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_CellChainingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_CellChainingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{BaseSetsStr}\\{CoverSetsStr}({DigitStr}) {ExofinsStr}{EndofinsStr}=&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ComplexFishStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_ComplexFishStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：环 {ChainStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ContinuousNiceLoopStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_ContinuousNiceLoopStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{CellsCountStr} 个单元格 {CellsStr} 构成多米诺环 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_DominoLoopStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_DominoLoopStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {Digit1Str} 和 {Digit2Str} 位于双值格 {StartCellStr} 和 {EndCellStr} 里，并在区域 {RegionStr} 里带有此两数交织起来的空矩形 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_EmptyRectangleIntersectionPairStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_EmptyRectangleIntersectionPairStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitStr} 位于区域 {RegionStr} 下拥有共轭对 {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_EmptyRectangleStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_EmptyRectangleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 位于单元格 {CellsStr} 里构成结构 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedRectangleType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedRectangleType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 位于单元格 {CellsStr} 里构成结构，带有额外数字 {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedRectangleType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedRectangleType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 位于单元格 {CellsStr} 里构成结构，在区域 {RegionStr} 带有数组，涉及单元格 {ExtraCellsStr} 的数字 {ExtraDigitsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedRectangleType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedRectangleType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 位于单元格 {CellsStr} 里构成结构，带有共轭对 {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedRectangleType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedRectangleType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：只有数字 {EspDigitStr} 在 {CellsStr} 里可以重复出现 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedSubsetPrincipleWithDuplicate {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedSubsetPrincipleWithDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：所有在 {CellsStr} 里面的数字都不相同 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedSubsetPrincipleWithoutDuplicate {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedSubsetPrincipleWithoutDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{CellStr} = {DigitStr}.
        /// </summary>
        internal static string TechniqueFormat_FullHouseStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_FullHouseStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：单元格 {CellsStr} 并带有{GuardianSingularOrPlural} {GuardianStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_GuardianStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_GuardianStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：在区域 {RegionStr} 里有 {CellStr} = {DigitStr}.
        /// </summary>
        internal static string TechniqueFormat_HiddenSingle {
            get {
                return ResourceManager.GetString("TechniqueFormat_HiddenSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitStr} 位于区域 {RegionStr} 里有隐性数组结构 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_HiddenSubsetStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_HiddenSubsetStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{CellStr} = {DigitStr}.
        /// </summary>
        internal static string TechniqueFormat_LastDigit {
            get {
                return ResourceManager.GetString("TechniqueFormat_LastDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitStr} 位于区域 {BaseSetStr}\\{CoverSetStr} 里有区块结构 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_LockedCandidatesStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_LockedCandidatesStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：网一共 {CellsCountStr} 个单元格 {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_MultisectorLockedSetsStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_MultisectorLockedSetsStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{CellStr} = {DigitStr}.
        /// </summary>
        internal static string TechniqueFormat_NakedSingleStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_NakedSingleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{DigitsStr} 位于区域 {RegionStr} 里有显性{SubsetName}结构 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_NakedSubsetStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_NakedSubsetStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitStr} 位于区域 {BaseSetStr}\\{CoverSetStr} 里有鱼结构{FinsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_NormalFishStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_NormalFishStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitStr} 有 POM 结构 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_PatternOverlayStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_PatternOverlayStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果所有这 {Number} 个候选数都为假的话，单元格 {PatternStr} 将产生致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternLockedTypeStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternLockedTypeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果 {CandidateStr} 全为假的话，单元格 {PatternStr} 将产生致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果所有位于单元格 {PatternStr} 里的数字 {ExtraDigitStr} 全部为假的话，则结构将产生致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：单元格 {PatternStr} 不会产生致命形式当且仅当数字 {DigitsStr} 在单元格 {CellsStr} 里会构成显性{SubsetName} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果涉及结构的、和共轭对 {ConjStr} 涉及外的数字被放在了共轭对上，单元格 {PatternStr} 将产生致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：可以使用强制链证得位于区域 {RegionStr} 的数字 {DigitStr} 全为假的矛盾 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_RegionChainingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_RegionChainingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 位于拐点 {PivotCellStr} 上，往单元格 {CellsStr} 上进行推理 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_RegularWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_RegularWingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{Cells1Str}({Digits1Str}) + {Cells2Str}({Digits2Str}) + {Cells3Str}({Digits3Str}) =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_SueDeCoq3DimensionStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_SueDeCoq3DimensionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：{IntersectionCellsStr}({IntersectionDigitsStr}) - {BlockCellsStr}({BlockDigitsStr}) &amp; {LineCellsStr}({LineDigitsStr}) =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_SueDeCoqStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_SueDeCoqStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：关于数字 {DigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_TemplateStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_TemplateStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitStr} 位于区域 {BaseRegionStr}\\{TargetRegionStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_TwoStrongLinksStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_TwoStrongLinksStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {Digit1Str} 和 {Digit2Str} 位于单元格 {LoopStr} 里构成结构 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueLoopType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueLoopType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {Digit1Str} 和 {Digit2Str} 位于单元格 {LoopStr} 里构成结构，带有额外数字 {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueLoopType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueLoopType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {Digit1Str} 和 {Digit2Str} 位于单元格 {LoopStr} 里构成结构，带有显性{SubsetName}、额外数字 {DigitsStr}，单元格为 {SubsetCellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueLoopType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueLoopType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {Digit1Str} 和 {Digit2Str} 位于单元格 {LoopStr} 里构成结构，带有共轭对 {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueLoopType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueLoopType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 位于单元格 {CellsStr} 里 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniquePolygonType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniquePolygonType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 位于单元格 {CellsStr} 里，带有一个额外数字 {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniquePolygonType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniquePolygonType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 位于单元格 {CellsStr} 里，在单元格 {ExtraCellsStr} 里带有额外数字 {ExtraDigitsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniquePolygonType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniquePolygonType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {DigitsStr} 位于单元格 {CellsStr} 里，带有一个关于数字 {ExtraCombStr} 的共轭组，位于单元格 {ConjRegionStr} 里 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniquePolygonType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniquePolygonType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {D1Str} 和 {D2Str} 在结构 {CellsStr} 里，X 为 {XDigitStr}、Y 为 {YDigitStr}、双值格为 {XYCellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangle2DOr3XStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangle2DOr3XStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {D1Str} 和 {D2Str} 在结构 {CellsStr} 里 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {D1Str} 和 {D2Str} 在结构 {CellsStr} 里，带额外数字 {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {D1Str} 和 {D2Str} 在结构 {CellsStr} 里，带额外数字 {DigitsStr} {OnlyKeywordZhCn}在区域 {RegionStr} 的 {CellsStr} 这几格里{AppearLimitKeyword} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {D1Str} 和 {D2Str} 在结构 {CellsStr} 里，并带共轭对 {ConjPairsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleWithConjugatePairStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleWithConjugatePairStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {D1Str} 和 {D2Str} 在结构 {CellsStr} 里，带一个简化版的融合待定数组存在于单元格 {MergedCellsStr} 里，涉及数字 {DigitsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleWithSueDeCoqStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleWithSueDeCoqStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {D1Str} 和 {D2Str} 在结构 {CellsStr} 里，带代数结构：设单元格 {TargetCellStr} 填入 X（X 是 {DigitsStr} 其一），则四个单元格将构成关于 X 和数字 {ExtraDigitStr} 的唯一矩形致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleWithUnknownCoveringStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleWithUnknownCoveringStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：数字 {D1Str} 和 {D2Str} 在结构 {CellsStr} 里，带一个简化版的融合待定数组存在于单元格 {MergedCellsStr} 里，涉及数字 {DigitsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleWithWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleWithWingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果候选数 {CandidateStr} 为假，则位于单元格 {CellsStr} 的数字 {DigitsStr} 将构成致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueSquareType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueSquareType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果数字 {ExtraDigitStr} 在单元格 {CellsStr} 里全部为假，则剩余数字 {DigitsStr} 在这些格子里将构成致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueSquareType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueSquareType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果数字 {ExtraDigitStr} 在单元格 {ExtraCellsStr} 里不构成显性{SubsetName}的话，则数字 {DigitsStr} 在单元格 {CellsStr} 里将构成致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueSquareType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueSquareType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：如果共轭区域 {ConjStr} 无法填入数字 {Digit1Str} 或者 {Digit2Str} 的话，数字 {DigitsStr} 在单元格 {CellsStr} 里将形成致命形式 =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueSquareType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueSquareType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}：从 {StartCellStr} 到 {EndCellStr}，共轭对为 {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_WWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_WWingStep", resourceCulture);
            }
        }
    }
}
