//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources1033 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources1033() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Resources.Resources1033", typeof(Resources1033).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  f.
        /// </summary>
        internal static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guardians.
        /// </summary>
        internal static string GuardianPlural {
            get {
                return ResourceManager.GetString("GuardianPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a guardian.
        /// </summary>
        internal static string GuardianSingular {
            get {
                return ResourceManager.GetString("GuardianSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string KeywordIn {
            get {
                return ResourceManager.GetString("KeywordIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1033.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , locked member 1:.
        /// </summary>
        internal static string LockedMemberQ {
            get {
                return ResourceManager.GetString("LockedMemberQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , locked member 2: .
        /// </summary>
        internal static string LockedMemberR {
            get {
                return ResourceManager.GetString("LockedMemberR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        internal static string OrKeywordWithSpaces {
            get {
                return ResourceManager.GetString("OrKeywordWithSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} from {BaseCellsStr} to {TargetCellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlmostLockedCandidatesStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlmostLockedCandidatesStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Two ALSes {Als1Str}, {Als2Str} connected by {ConjStr}, W = {WStr}, X = {XStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlmostLockedSetsWWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlmostLockedSetsWWingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {Als1Str} -&gt; {BridgeStr} -&gt; {Als2Str}, X = {XStr}, Y = {YStr}, Z = {ZStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlmostLockedSetsXyWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlmostLockedSetsXyWingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: ALS #1: {Als1Str}, ALS #2: {Als2Str}, X = {XStr}{ZResultStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlmostLockedSetsXzRule {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlmostLockedSetsXzRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Chain {ChainStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AlternatingInferenceChainStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AlternatingInferenceChainStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr} with hidden single: if cell {BaseCellStr} is filled with the digit {Digit1Str}, region {RegionStr} will only contain a cell {TargetCellStr} can be filled with that digit, but will raise the deadly pattern =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_AvoidableRectangleWithHiddenSingleStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_AvoidableRectangleWithHiddenSingleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: It can be proved to be a contradiction if {AnchorIsTrueOrFalseStr} is {AnchorIsNotOnStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BinaryChainingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BinaryChainingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: If the cell {CellStr} only contains the digits {Digit1Str} and {Digit2Str} (or one of those two), the loop {LoopStr} will form an error structure =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueOddagonType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueOddagonType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: If all digit {ExtraDigitStr} in cells {LoopStr} are removed, the loop will from an error structure =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueOddagonType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueOddagonType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: To avoid the structure {LoopStr} of digits {Digit1Str} and {Digit2Str} error, the only way is to form the subset (digits {DigitsStr} in cells {ExtraCellsStr}) =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueOddagonType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueOddagonType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: True candidates: {CandidatesStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveMultipleStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveMultipleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {ExtraDigitStr} with cells {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: True candidates {TrueCandidatesStr} with {SubsetTypeStr} {SizeStr} {ExtraDigitsStr} in cells {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in cells {CellsStr} with conjugate pair {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitStr} with cells {CellsStr}, with extra cell {ExtraCellStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BivalueUniversalGraveXzStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BivalueUniversalGraveXzStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Try {ContradictionSeriesStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_BowmanBingoStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BowmanBingoStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {AssignmentStr}.
        /// </summary>
        internal static string TechniqueFormat_BruteForceStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_BruteForceStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: It can be proved using chains that all digits are false from {SourceCellStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_CellChainingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_CellChainingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitStr} in {BaseSetsStr}\\{CoverSetsStr} {ExofinsStr}{EndofinsStr}=&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ComplexFishStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_ComplexFishStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Loop {ChainStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ContinuousNiceLoopStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_ContinuousNiceLoopStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {CellsCountStr} cells {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_DominoLoopStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_DominoLoopStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {Digit1Str}, {Digit2Str} in bivalue cells {StartCellStr} and {EndCellStr} with empty rectangle in {RegionStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_EmptyRectangleIntersectionPairStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_EmptyRectangleIntersectionPairStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitStr} in {RegionStr} with conjugate pair {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_EmptyRectangleStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_EmptyRectangleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedRectangleType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedRectangleType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in {CellsStr} with extra digit {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedRectangleType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedRectangleType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in {CellsStr} with {ExtraDigitsStr} in cells {ExtraCellsStr} in {RegionStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedRectangleType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedRectangleType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in {CellsStr} with the conjugate pair {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedRectangleType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedRectangleType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Only the digit {EspDigitStr} can be duplicate in cells {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedSubsetPrincipleWithDuplicate {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedSubsetPrincipleWithDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: All digits can&apos;t be duplicate in cells {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_ExtendedSubsetPrincipleWithoutDuplicate {
            get {
                return ResourceManager.GetString("TechniqueFormat_ExtendedSubsetPrincipleWithoutDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {CellStr} = {DigitStr}.
        /// </summary>
        internal static string TechniqueFormat_FullHouseStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_FullHouseStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Cells {CellsStr} with {GuardianSingularOrPlural} {GuardianStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_GuardianStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_GuardianStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {CellStr} = {DigitStr} in {RegionStr}.
        /// </summary>
        internal static string TechniqueFormat_HiddenSingle {
            get {
                return ResourceManager.GetString("TechniqueFormat_HiddenSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitStr} in {RegionStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_HiddenSubsetStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_HiddenSubsetStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {CellStr} = {DigitStr}.
        /// </summary>
        internal static string TechniqueFormat_LastDigit {
            get {
                return ResourceManager.GetString("TechniqueFormat_LastDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitStr} in {BaseSetStr}\\{CoverSetStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_LockedCandidatesStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_LockedCandidatesStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {CellsCountStr} cells {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_MultisectorLockedSetsStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_MultisectorLockedSetsStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {CellStr} = {DigitStr}.
        /// </summary>
        internal static string TechniqueFormat_NakedSingleStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_NakedSingleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in {RegionStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_NakedSubsetStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_NakedSubsetStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitStr} in {BaseSetStr}\\{CoverSetStr}{FinsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_NormalFishStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_NormalFishStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digit {DigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_PatternOverlayStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_PatternOverlayStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Cells {PatternStr} will be a deadly pattern if{Quantifier}{Number} {SingularOrPlural} {CandidateStr} {BeVerb} false =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternLockedTypeStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternLockedTypeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Cells {PatternStr} will be a deadly pattern if {CandidateStr} is false =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Cells {PatternStr} will be a deadly pattern if all the extra digits {ExtraDigitStr} in pair cells is false =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Cells {PatternStr} won&apos;t be a deadly pattern if and only if digits {DigitsStr} in cells {CellsStr} is a naked {SubsetName} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Cells {PatternStr} will be a deadly pattern if another digit in either cells lying on the conjugate pair {ConjStr} is true =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_QiuDeadlyPatternType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_QiuDeadlyPatternType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: It can be proved using chains that digit {DigitStr} from {RegionStr} are false =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_RegionChainingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_RegionChainingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in {PivotCellStr} with {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_RegularWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_RegularWingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {Cells1Str}({Digits1Str}) + {Cells2Str}({Digits2Str}) + {Cells3Str}({Digits3Str}) =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_SueDeCoq3DimensionStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_SueDeCoq3DimensionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {IntersectionCellsStr}({IntersectionDigitsStr}) - {BlockCellsStr}({BlockDigitsStr}) &amp; {LineCellsStr}({LineDigitsStr}) =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_SueDeCoqStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_SueDeCoqStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digit {DigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_TemplateStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_TemplateStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitStr} in {BaseRegionStr}\\{TargetRegionStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_TwoStrongLinksStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_TwoStrongLinksStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {Digit1Str}, {Digit2Str} in cells {LoopStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueLoopType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueLoopType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {Digit1Str}, {Digit2Str} in cells {LoopStr} with the extra digit {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueLoopType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueLoopType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {Digit1Str}, {Digit2Str} in cells {LoopStr} with the naked {SubsetName} with extra digits {DigitsStr} in cells {SubsetCellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueLoopType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueLoopType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {Digit1Str}, {Digit2Str} in cells {LoopStr} with the conjugate pair {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueLoopType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueLoopType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in cells {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniquePolygonType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniquePolygonType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in cells {CellsStr} with the extra digit {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniquePolygonType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniquePolygonType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in cells {CellsStr} with the digits {ExtraDigitsStr} in cells {ExtraCellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniquePolygonType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniquePolygonType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {DigitsStr} in cells {CellsStr} with the conjugate region {ConjRegionStr} of the extra digits {ExtraCombStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniquePolygonType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniquePolygonType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr}, with X = {XDigitStr}, Y = {YDigitStr} and a bi-value cell {XYCellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangle2DOr3XStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangle2DOr3XStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr}, with the extra digit {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr}, with the digit {DigitsStr} in {OnlyKeyword}cells {CellsStr} in {RegionStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr} with {Prefix}conjugate pair{Suffix} {ConjPairsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleWithConjugatePairStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleWithConjugatePairStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr} with guardian: digit {GuardianDigitStr} in cells {GuardianCellsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleWithGuardianStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleWithGuardianStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr}, with a generalized Sue de Coq in cells {MergedCellsStr} of digits {DigitsStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleWithSueDeCoqStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleWithSueDeCoqStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr}, with unknown covering: Suppose {TargetCellStr} is filled with the unknown digit X (X is {DigitsStr}), then 4 cells form a UR deadly pattern of digit X and {ExtraDigitStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleWithUnknownCoveringStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleWithUnknownCoveringStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {D1Str} and {D2Str} in {CellsStr}, with a wing (pivots: {PivotsStr}, with digits: {DigitsStr} in cells {CellsStr}) =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueRectangleWithWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueRectangleWithWingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {DigitsStr} in cells {CellsStr} will form a deadly pattern if the candidate {CandidateStr} is false =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueSquareType1Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueSquareType1Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {DigitsStr} in cells {CellsStr} will form a deadly pattern if the extra digit {ExtraDigitStr} is all false in the pattern =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueSquareType2Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueSquareType2Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {DigitsStr} in cells {CellsStr} can be avoid to form a deadly pattern if and only if the digits {ExtraDigitStr} in cells {ExtraCellsStr} form a naked {SubsetName} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueSquareType3Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueSquareType3Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: Digits {DigitsStr} in cells {CellsStr} can avoid to form a deadly pattern if and only if the conjugate region {ConjStr} can&apos;t set the digit neither {Digit1Str} nor {Digit2Str} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_UniqueSquareType4Step {
            get {
                return ResourceManager.GetString("TechniqueFormat_UniqueSquareType4Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {StartCellStr} to {EndCellStr} with conjugate pair {ConjStr} =&gt; {ElimStr}.
        /// </summary>
        internal static string TechniqueFormat_WWingStep {
            get {
                return ResourceManager.GetString("TechniqueFormat_WWingStep", resourceCulture);
            }
        }
    }
}
