global using System;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.CommandLine;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.CodeGen;
global using System.Drawing;
global using System.IO;
global using System.Linq;
global using System.Net.NetworkInformation;
global using System.Numerics;
global using System.Reactive.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.Versioning;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using Mirai.Net.Data.Events.Concretes.Bot;
global using Mirai.Net.Data.Events.Concretes.Group;
global using Mirai.Net.Data.Events.Concretes.Request;
global using Mirai.Net.Data.Messages;
global using Mirai.Net.Data.Messages.Concretes;
global using Mirai.Net.Data.Messages.Receivers;
global using Mirai.Net.Data.Shared;
global using Mirai.Net.Modules;
global using Mirai.Net.Sessions;
global using Mirai.Net.Sessions.Http.Managers;
global using Mirai.Net.Utils.Scaffolds;
global using Sudoku.Concepts;
global using Sudoku.Drawing;
global using Sudoku.Generating;
global using Sudoku.Platforms.QQ.Data;
global using Sudoku.Platforms.QQ.Data.AppLifecycle;
global using Sudoku.Platforms.QQ.Data.Gaming;
global using Sudoku.Platforms.QQ.Data.Parsing;
global using Sudoku.Platforms.QQ.Data.Parsing.ValueConverters;
global using Sudoku.Platforms.QQ.Data.Puzzles;
global using Sudoku.Platforms.QQ.Data.Roles;
global using Sudoku.Platforms.QQ.Data.Scoring;
global using Sudoku.Platforms.QQ.Data.Shopping;
global using Sudoku.Platforms.QQ.Data.Storage;
global using Sudoku.Platforms.QQ.Modules;
global using Sudoku.Platforms.QQ.Modules.Group;
global using Sudoku.Preprocessing.AutoFiller;
global using Sudoku.Presentation;
global using Sudoku.Presentation.Nodes;
global using Sudoku.Runtime.AnalysisServices;
global using Sudoku.Solving.Logical;
global using Sudoku.Solving.Logical.Techniques;
global using static System.Algorithm.Sequences;
global using static System.Math;
global using static System.Text.Json.JsonSerializer;
global using static Sudoku.Platforms.QQ.Data.AppLifecycle.EnvironmentData;
global using static Sudoku.Platforms.QQ.ProjectWideConstants;
global using Group = Mirai.Net.Data.Shared.Group;
global using SpecialFolder = System.Environment.SpecialFolder;
global using File = System.IO.File;
