using System;

namespace Sudoku.DocComments
{
	/// <summary>
	/// (Deconstruct method) Deconstruct the instance to multiple values.
	/// </summary>
	/// <remarks>
	/// <para>
	/// The method should be customed when the type is a normal <see langword="struct"/> or <see langword="class"/>.
	/// If the method is a <see langword="record"/>, the method will be generated by the comipler and returns all
	/// properties from those <see langword="out"/> parameters.
	/// </para>
	/// <para>
	/// Please note that the deconstruct methods can contain more than 8 <see langword="out"/> parameters, although
	/// a normal <see cref="ValueTuple"/> can only contain at most 8 parameters.
	/// </para>
	/// </remarks>
	/// <seealso cref="ValueTuple"/>
	public sealed class DeconstructMethod
	{
	}
}
