global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Runtime.CompilerServices;
global using System.Text;
global using Sudoku.Data;
global using Sudoku.Globalization;
global using Sudoku.Resources;
global using Sudoku.Solving.BruteForces;
global using Sudoku.Versioning;
global using static System.Math;
global using static Sudoku.Constants.Tables;
